### ISSUE TITLE
Desenvolver menu para custom post type de eventos - RedETSA

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/wordpress-themes#101]
Bom dia @wilsonmoura 
Por favor desenvolver solução para menu lateral do que permita navegação nos custom post type de eventos.

Link de exemplo
https://redetsa.teste.bvsalud.org/eventos/xi-encuentro-anual-2020/
![image](https://user-images.githubusercontent.com/48724136/158376793-f6adb89c-61e5-444d-81a2-4b73da636fc5.png)

**Comment by marcioalvessilva** [comment]
@wilsonmoura custom post type criado, pode dar continuidade, qualquer coisa estou à disposição.
Grato!

**Comment by wilsonmoura** [comment]
@marcioalvessilva ajustes realizados no ambiente de testes. Favor validar.

**Comment by marcioalvessilva** [comment]
Grato @wilsonmoura , fiz os teste estão corretos.
