### ISSUE TITLE
Criar tema de WP para BVS Moçambique

### ISSUE THREAD

**Issue by sousajul** [bireme/wordpress-themes#102]
Marina Criar tema de WP para BVS Moçambique na instância de teste: http://mocambique.teste.eportuguese.org de acordo com o Mockup aprovado.

![bvs-mocambique](https://user-images.githubusercontent.com/13439949/161841026-488a6cc1-1630-4d04-aa65-10e273429a16.png)

**Comment by sousajul** [comment]
@pierrima veja a proposta enviada por Moçambique, tentar juntas as duas propostas.

![Modelo BVS Draft_4-02](https://user-images.githubusercontent.com/13439949/162797225-29c035e7-dc3e-452f-9735-bdf31f5cfb95.png)

**Comment by sousajul** [comment]
@pierrima seguem encaminhamentos de nossa reunião, de acordo com a proposta enviada pela equipe do INS, veja se prefere enviar uma outra proposta de mockup antes de iniciarmos o desenvolvimento do tema.

Realizar as seguintes alterações:
1. Incluir a caixa de pesquisa abaixo do menu ou do carrossel de destaques - equipe BIREME avaliar melhor posição
2. Como o carrossel de destaques foi incluído no começo do portal, retirar a outra seção de "Destaques" que foi criada ao lado do RSS das "últimas publicações" e no lugar incluir a seção "Sites Relacionados" - BIREME
3. Colocar a seção "Instituições cooperantes" no rodapé antes da informação dos responsáveis pelo portal - BIREME
4. Incluir a seção "Sobre a Iniciativa ePORTUGUESe" de acordo com a proposta inicial que enviamos - BIREME


Sobre o logo da Rede ePORTUGUESe, será agendada uma reunião para discutir sobre o tema.

**Comment by pierrima** [comment]
Olá Juliana, boa tarde

Segue a proposta atualizada.
Abraços

![proposta](https://user-images.githubusercontent.com/13052947/165520497-64cad4b7-f7eb-404e-a007-23b7e5313b61.png)

**Comment by sousajul** [comment]
@pierrima atualizar a proposta de desenho com a inclusão da seção "Rede de Bibliotecas Virtuais em Saúde ePORTUGUESe" com as bandeiras dos países, conforme desenho anexo. 

- No banner colocas as iniciais e BVS em maiúscula.

![Proposta-AI-BVS-MZ-20220516](https://user-images.githubusercontent.com/13439949/168928134-d50441ff-281c-44ca-b6f2-20981f080b9b.png)

**Comment by pierrima** [comment]
Olá Juliana, boa tarde

Segue a proposta com as alterações indicadas. Abraços
![proposta3](https://user-images.githubusercontent.com/13052947/169899045-90472d93-74af-4360-815f-8256af968dbc.png)

**Comment by sousajul** [comment]
@pierrima proposta aprovada. Pode iniciar aplicação.

Na seção Rede ePORTUGUESe, incluir a bandeira de Guiné Equatorial

**Comment by sousajul** [comment]
@marcioalvessilva precisamos iniciar essa atividade, por favor, veja com o Mori o que é necessário para iniciarmos. Se preciso podemos fazer uma reunião.

**Comment by marcioalvessilva** [comment]
Etapa Finalizada!
