### ISSUE TITLE
No novo tema do Portal APS avaliar uso da seção "FIQUE POR DENTRO" 

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/wordpress-themes#105]
@pierrima conforme verificado pela @alvesmarilda no novo tema do Portal APS favor considerar se estaremos mostrando a últimas SOFs registradas e caso afirmativo usar a RSS do repositório (https://aps-repo.bvs.br/aps/feed/)

![image](https://user-images.githubusercontent.com/349287/167624936-db456bfa-d000-4610-adc3-e3b522e75870.png)

Obrigado

**Comment by marcioalvessilva** [comment]
Finalizado!
