### ISSUE TITLE
Elaborar figura para atualização das quantidades no DeCS

### ISSUE THREAD

**Issue by acecampos** [bireme/wordpress-themes#107]
@marcioalvessilva por favor, elaborar outra figura para substituir a que está abaixo:
![image](https://user-images.githubusercontent.com/35345406/170762812-d02b9be6-6918-4d3d-bd16-95713f5b2f13.png)

Em um futuro próximo, fornecerei aqui os dados numéricos para que você possa elaborar com tranquilidade.

Obrigada!

**Comment by acecampos** [comment]
@marcioalvessilva,
![image](https://user-images.githubusercontent.com/35345406/176145430-5bba1798-7410-4fcf-9fc5-ec8fcd0feb69.png)
Peço, por favor, para atualizar os números e a figura, ajustando os dados indicados.
Grata!

**Comment by marcioalvessilva** [comment]
Boa tarde!
Dados atualizados, por favor validar

**PT**
![image](https://user-images.githubusercontent.com/48724136/176509671-e8b8a9e9-545b-4942-bf0c-6a1163973e31.png)


**Es**
![image](https://user-images.githubusercontent.com/48724136/176509738-b7c0bf8d-65e1-4482-995b-bd1257a4c2e2.png)


**En**
![image](https://user-images.githubusercontent.com/48724136/176509795-6ab19001-fb4e-46ff-ac6d-c65d412381e4.png)


**Fr**
![image](https://user-images.githubusercontent.com/48724136/176509833-a8dec6d9-566a-4a1f-9b6e-e32df6e96cbd.png)

**Comment by acecampos** [comment]
@marcioalvessilva por favor, da figura em FR retirar o et da frente do Surveillance e também tirar o ponto depois de santé.

**Comment by marcioalvessilva** [comment]
Atualizado versão FR
![image](https://user-images.githubusercontent.com/48724136/176514062-fdf8baaa-8cc6-4296-b7e0-e1ad3ce82388.png)

**Comment by acecampos** [comment]
@marcioalvessilva Gráficos validados. Obrigada.
