### ISSUE TITLE
Elaborar figura com números atualizados da edição 2022 do DeCS

### ISSUE THREAD

**Issue by acecampos** [bireme/wordpress-themes#108]
@marcioalvessilva, conforme figura abaixo, 

![image](https://user-images.githubusercontent.com/35345406/170764491-741c88de-cdf5-4bb5-8254-eb07831499ba.png)

por favor:

- Substituir por “Números da edição 2022”.
- Elaborar figura com números atualizados a serem definidos futuramente em um próximo comentário nesse issue.

**Comment by marcioalvessilva** [comment]
Finalizado!
