### ISSUE TITLE
Modificação da página inicial do DeCS

### ISSUE THREAD

**Issue by acecampos** [bireme/wordpress-themes#109]
@marcioalvessilva, conforme gravação de reunião no Teams e de acordo com a figura abaixo, que representa a página inicial do DeCS,

![image](https://user-images.githubusercontent.com/35345406/170764200-ef4125a1-7a67-4390-895c-64293ec45d48.png)

solicito, por favor:

1. Colocar o texto abaixo no local indicado na figura (se for de acesso exclusivo seu. Se não for, nós podemos inserir, ok?)

"A pesquisa oferece cinco métodos de busca
· **Qualquer termo**: pesquisa pela palavra digitada no campo de busca em todos os termos, Descritores, Termos Alternativos e Qualificadores, independentemente da ordem da palavra no termo.
· **Termo exato**: pesquisa pelo termo que corresponde exatamente à palavra digitada.
· **ID do descritor**: pesquisa pelo identificador único do registro DeCS/MeSH e recupera tanto descritores quanto qualificadores.
· **Código Hierárquico**: pesquisa por código da hierarquia DeCS/MeSH e recupera o registro que possui a posição específica na árvore de conceitos.
· **Qualquer qualificador**: pesquisa pela palavra digitada no campo de busca em todos os Qualificadores, independentemente da ordem da palavra no termo.

Para pesquisar por parte da palavra ou código utilize o truncador * ou **$** antes ou após a sequência digitada.

Veja mais orientações no Guia como usar o DeCS/MeSH.

Não encontrou o assunto que procura? Sugira um termo novo."

2.  Substituir pelo novo texto a seguir: “DeCS/MeSH Finder: localize automaticamente termos do tesauro presentes em seu documento”, conforme indicado na figura acima.

3. Remover momentaneamente as figuras indicadas, que serão reinseridas após a atualização com as novas quantidades, conforme figura abaixo:
![image](https://user-images.githubusercontent.com/35345406/170764288-dd6c326c-8b29-4e32-b7d0-1fd9c29cfd25.png)

Grata!

**Comment by acecampos** [comment]
Links:
ESP
Haga sugerencia de un nuevo término: https://docs.google.com/forms/d/e/1FAIpQLSc6G9QO14h9Rv6GI6dr2wmk1heg9db5Cyp8aNpu1WVF8shsiA/viewform?usp=sf_link

POR
Sugira um termo novo:
https://docs.google.com/forms/d/e/1FAIpQLSc9uq1L-qkVjaJKXddss_UxzTiFoU9yytPYCMWNdV8EdbLuZg/viewform?usp=sf_link

ING
Suggest a new term:
https://docs.google.com/forms/d/e/1FAIpQLScMO2k1CnrcpjNVr0ROGL1frQZxliQ4Q9_gb4dpFjOqLw2dgA/viewform?usp=sf_link

**Comment by acecampos** [comment]
FRA
La recherche offre cinq méthodes de recherche :
Tout terme : recherche le mot tapé dans le champ de recherche dans tous les termes, descripteurs et termes alternatifs, quel que soit l'ordre des mots dans le terme.
Terme exact : recherche le terme qui correspond exactement au mot tapé.
ID du descripteur : recherche l'identifiant unique de l'enregistrement DeCS/MeSH des descripteurs.
Code hiérarchique : recherche par code hiérarchique DeCS/MeSH et récupère l'enregistrement qui a la position spécifique dans l'arbre conceptuel.
Tout qualificatif : recherche par le mot tapé dans le champ de recherche dans tous les qualificatifs, quel que soit l'ordre des mots dans le terme.
Pour effectuer une recherche par segment du mot ou du code, utilisez le troncateur * ou $ avant ou après la séquence tapée.

**Comment by acecampos** [comment]
FRE
Suggérer un nouveau terme:

**Comment by marcioalvessilva** [comment]
Finalizado!
