### ISSUE TITLE
Criação de um modal com o texto “Edição 2022 disponível”

### ISSUE THREAD

**Issue by acecampos** [bireme/wordpress-themes#110]
@marcioalvessilva 
De acordo com as figuras representando as páginas do portal:

![image](https://user-images.githubusercontent.com/35345406/170764371-4cb1f427-3c5b-4471-ad6b-828c8cd14e1b.png)

Solicito, por favor:
- A página inicial do portal ser só de pesquisa (no DeCS e no DeCS Finder), conforme simulado na figura acima.
- Linkar o logo do DeCS/MeSH para a página “Sobre o DeCS”
- Alterações no menu (a @lucianaPRB já fez algumas mudanças no ambiente de testes)
- Criação de um modal com o texto “Edição 2022 disponível” e reservar esse espaço para modal com informações temporárias

**Comment by marcioalvessilva** [comment]
Finalizado!
