### ISSUE TITLE
Criar página de erro no portal da LILACS

### ISSUE THREAD

**Issue by suelisuga** [bireme/wordpress-themes#111]
Solicito criação de página de erro 404 no portal da LILACS.

Sugestão de layout aprovado com gerência PFI:

![image](https://user-images.githubusercontent.com/13105683/172468172-e2d395ec-82ff-469c-9ae5-95d5ed5d7fab.png)

### Português

Ops, que pena! A página que você acessou está indisponível ou não existe. Você pode tentar as opções abaixo ou voltar a acessar mais tarde.

Opções de Links:

- Pesquisa na base de dados LILACS
- Lista de periódicos indexados na base de dados LILACS
- Tutorial de pesquisa na LILACS
- Sobre a Rede LILACS
- Como indexar um periódico na base LILACS
- Como dar visibilidade à produção científica da sua instituição na LILACS?
- Sua opinião sobre o portal LILACS

Não encontrou uma opção que responda a sua necessidade? Volte para o Portal da LILACS ou entre em contato conosco

### Inglês

Oops, what a pity! The page you accessed is unavailable or does not exist.

You can try the options below or come back later.

Link Options:

- LILACS database search
- List of journals indexed in LILACS database
- LILACS search tutorial
- About the LILACS Network
- How to index a journal in the LILACS database
- How to give visibility to the scientific production of your institution in LILACS?
- Your opinion about the LILACS portal

Didn't find an option that answers your need? Return to the LILACS Portal or contact us

### Español

¡Vaya, qué pena! La página a la que accedió no está disponible o no existe.

Puede probar las siguientes opciones o volver a iniciar sesión más tarde.

Opciones de enlace:

- Búsqueda en la base de datos de LILACS
- Lista de revistas indexadas en la base de datos LILACS
- Tutorial de búsqueda en LILACS
- Red LILACS
- Cómo indexar un diario en la base de datos LILACS
- ¿Cómo dar visibilidad a la producción científica de su institución en LILACS?
- Tu opinión sobre el portal de LILACS

¿No encontró una opción que responda a su necesidad? Regresar al portal de LILACS o contáctenos

**Comment by wilsonmoura** [comment]
@suelisuga ajustes realizados no ambiente de testes. Para apoiar nessa atividade, utilizamos o plugin [404page](https://br.wordpress.org/plugins/404page/), que permite redirecionar as páginas com erro 404 para uma página pré-definida.

**Comment by wilsonmoura** [comment]
@suelisuga ajustes realizados no ambiente de testes. Para apoiar nessa atividade, utilizamos o plugin [404page](https://br.wordpress.org/plugins/404page/), que permite redirecionar as páginas com erro 404 para uma página predefinida.
