### ISSUE TITLE
Criar página de bloqueio para BVS Controle e cancêr

### ISSUE THREAD

**Issue by marcoslmori** [bireme/wordpress-themes#116]
Marcio, por favor, criar uma página elaborada com a identidade visual da BVS Controle e Cancer com o texto abaixo para as instancias https://controlecancer.bvs.br/ e https://pesquisa.bvsalud.org/controlecancer/

instancia teste: https://controlecancer.teste.bvs.br/

Obrigado, 

Mori

-----------------------------------
Prezados,

Solicito o bloqueio do portal da BVS Prevenção e Controle do Câncer durante o período eleitoral no Brasil em respeito a Instrução Normativa nº 1, de 11 de abril de 2018. Gostaríamos de solicitar a manutenção de uma mensagem explicativa ao usuários com o seguinte:

"Em respeito a Instrução Normativa nº 1, de 11 de abril de 2018, e por recomendações contidas em ofício-circular da Secretaria Especial de Comunicação Social da Presidência da República (Secom/PR),  o conteúdo informativo veiculado na BVS Prevenção e Controle de Câncer será bloqueado a partir de 2 de julho, devido ao início do período eleitoral. Estaremos disponíveis para atender os usuários em suas pesquisas em bases de dados por meio de acesso restrito aos bibliotecários. Os usuários podem fazer solicitações de busca e publicações através do e-mail: [bvs@inca.gov.br](mailto:bvs@inca.gov.br) ou por meio do [formulário] https://docs.google.com/forms/d/e/1FAIpQLScdxYtjLV9NJ1ZXeNpGxTtgS1hu8r1MMCnpRpOqn4j3YEC5-g/viewform 

Copio os gestores do Instituto Nacional de Câncer que estão acompanhando essa demanda.

Atenciosamente,

Camila Belo Tavares Ferreira
Coordenadora da BVS Prevenção e Controle de Câncer
Secretaria Executiva
Instituto Nacional de Câncer
Ministério da Saúde

**Comment by marcioalvessilva** [comment]
@marcoslmori, segue anexo html,  por favor validar

[bvs-cancer.zip](https://github.com/bireme/wordpress-themes/files/9041042/bvs-cancer.zip)

Modelo!
![image](https://user-images.githubusercontent.com/48724136/177193200-75290468-46e8-4d09-b16a-1d17a314a208.png)

**Comment by marcioalvessilva** [comment]
Seguem atualizações, @marcoslmori por favor atualizar no servidor.

[bvs-cancer.zip](https://github.com/bireme/wordpress-themes/files/9066399/bvs-cancer.zip)
Grato!

**Comment by marcoslmori** [comment]
@marcioalvessilva  feito chamado para o ITI  chamado 8589 link direto:
http://suporte.bvs.br//ocomon/geral/ticket_show.php?numero=8589&id=wlYEWPddHFodkesn5JVps2Vtqr4%3

**Comment by sousajul** [comment]
Ajustes realizados e mensagem de bloqueio validada.
