### ISSUE TITLE
configurar a página de noticias da BVS SMS-SP

### ISSUE THREAD

**Issue by sousajul** [bireme/wordpress-themes#118]
Configurar a página "Ver todas" de noticias da BVS SMS-SP considerar:

- Ver se na URL é possível tirar o "category" deixando apenas URL/noticias (https://sms.sp-new.teste.bvs.br/category/noticias/)
- Incluir thumbnail da imagem que está na noticia
- Ver se é possível inserir a caixa de busca
- Inserir paginação
- Traduzir a informação que vai na noticia (Leave a Comment / Notícias / By Andrea Silva) e o [Read More »]
- Em cada noticia incluir data 
- No botão "ver todas" remeter para a página que mostra todas as noticias.
![image](https://user-images.githubusercontent.com/13439949/177631571-715cbea3-b1e4-4f56-adf8-357dbc8abff2.png)

Em cada noticia individual
- Em cada noticia incluir data 
-  Traduzir a informação que vai na noticia (Leave a Comment / Notícias / By Andrea Silva) e o [Read More »]
- Traduzir conteúdos destacados para o português

![image](https://user-images.githubusercontent.com/13439949/177631913-72f3100a-0529-4930-b8fa-78ca8b599f31.png)

Ajustar os seguintes itens na Home:
- Fundo no banner que está com cores diferentes onde tem o logo
- Retirar espaço em branco que está entre a seção Rede BVS SMS São Paulo e o rodapé
- Incluir um plugin de breadcrumbs
- Alinhar a barra de acessibilidade com o restante do conteúdo

Att.

**Comment by marcioalvessilva** [comment]
Finalizados!
