### ISSUE TITLE
Ajustar interface da BVS Saúde Ambiental e Engenharia de Saúde Pública

### ISSUE THREAD

**Issue by barrosjo** [bireme/wordpress-themes#119]
https://saudeambiental.bvs.br/
[marcaFunasaAtual (1).zip](https://github.com/bireme/wordpress-themes/files/9102161/marcaFunasaAtual.1.zip)
[AjustesBVS-01-06-2022.pdf](https://github.com/bireme/wordpress-themes/files/9102164/AjustesBVS-01-06-2022.pdf)

**Comment by marcioalvessilva** [comment]
Olá @wilsonmoura, pode por favor trocar o link imagem, não tenho acesso conforme conversamos. Grato!!!
Link: http://saudeambiental.bvs.br/marcafunasaatual/
Isso atende a solicitação abaixo

1. Inicialmente, a logomarca da Funasa dever ser trocada pela logo normal (sem o símbolo de 30 anos), conforme arquivo enviado em anexo, tendo em vista que encerrou-se em abril/2022 o período comemorativo de uso do selo de 30 anos;

Grato!

**Comment by wilsonmoura** [comment]
@marcioalvessilva ajustes realizados. Favor solicitar a transferência do arquivo abaixo localizado no servidor de testes `dolomita02` para o servidor de produção `dolomita11`:

    /home/apps/bvs.br/wp-saudeambiental/htdocs/wp-content/plugins/bvs-site/bvs-themes/bvs-2012/bireme_archives/custom/custom.js

**Comment by wilsonmoura** [comment]
@marcioalvessilva ajustes realizados. Favor solicitar ao ITI a transferência do arquivo abaixo localizado no servidor de testes para o servidor de produção:

    /home/apps/bvs.br/wp-saudeambiental/htdocs/wp-content/plugins/bvs-site/bvs-themes/bvs-2012/bireme_archives/custom/custom.js

**Comment by marcioalvessilva** [comment]
Finalizado!
