### ISSUE TITLE
Atualizar links das estratégias de buscas da página de BRISA na instância da RedTsA e publicar 

### ISSUE THREAD

**Issue by marcoslmori** [bireme/wordpress-themes#121]
Atualizar links das estratégias de buscas da página de BRISA na instância da RedTsA e publicar 
Link: https://docs.google.com/document/d/1jJllqv4KdDWysnWYZ9-sdr_e2p90OvS8/edit#heading=h.7o6jqxo6dsuz

**Comment by marcioalvessilva** [comment]
Finalizado!
