### ISSUE TITLE
Configurar a página dos plugins LIS, Direve e Multimidia da BVS SMS

### ISSUE THREAD

**Issue by sousajul** [bireme/wordpress-themes#123]
https://sms.sp.bvs.br/lis/
https://sms.sp.bvs.br/direve/
https://sms.sp.bvs.br/multimedia/ (em fase de instalação)

- Configurar o banner, que repete o menu e uma faixa com o nome BVS SMS
- Ajustar o fundo do banner com o fundo das imagens do logo da BVS e da Prefeitura
- Configurar a barra azul do menu que está 100% na página e o conteúdo menor nas laterais
- Verificar bredcrumbs que está sobreposto ao menu
- Verificar o rodapé que não está sendo replicado nas páginas

**Comment by marcioalvessilva** [comment]
- Configurar o banner, que repete o menu e uma faixa com o nome BVS SMS
    - **Removido** 
- Ajustar o fundo do banner com o fundo das imagens do logo da BVS e da Prefeitura
     - **Alterado** 
- Configurar a barra azul do menu que está 100% na página e o conteúdo menor nas laterais
  - **Alterado - mas por favor validar**
- Verificar bredcrumbs que está sobreposto ao menu
  - **Corrigido**
- Verificar o rodapé que não está sendo replicado nas páginas
  - **Para mim esta ok, apenas nas paginas liz, direve e multimida que não tem por ser paginas do plugin** me informa de devem aparecer

**Comment by sousajul** [comment]
@marcioalvessilva de acordo com as informações do @wilsonmoura e @marcoslmori a resposta para o item abaixo é [sim], na página dos plugins o rodapé deve seguir o modelo da página da BVS assim como é o banner.

Verificar o rodapé que não está sendo replicado nas páginas
Para mim esta ok, apenas nas paginas liz, direve e multimida que não tem por ser paginas do plugin me informa de devem aparecer

**Comment by sousajul** [comment]
Realizado.
