### ISSUE TITLE
Realizar ajustes na BVS Bolívia

### ISSUE THREAD

**Issue by sousajul** [bireme/wordpress-themes#124]
https://bolivia.teste.bvsalud.org/

Mejorar la configuración de los contenidos:

1. Hay que ajustar la responsividad del portal, en el encabezado los logos están cortados 
2. Hay que ajustar el tipo de las funtes, ejemplo: en la sección que están los RSS el tipo de fuente está distinta de los demas contenidos
3. Hay que mejorar la calidad de las imagines como un todo del portal, Uds. pueden enviarnos las imagenes que intentamos mejoralas (aguardando)
4. Hay que instalar el plugin de breadcrumbs y google analytics
5. Hay que crear la propuesta de página secundaria para las BVS temáticas, voy a trabajar con nuestro diseñador y hacerles una propuesta, pero para el lanzamiento puede quedar así

**Comment by sousajul** [comment]
@marcioalvessilva alguma retorno? o Lançamento está previsto para o dia 22 ou 30.


Abraços,

**Comment by marcioalvessilva** [comment]
Olá @sousajul 
- Fiz ajustes na home de responsividade e no topo e footer de todo o site.
- Não recebi nenhuma imagem para fazer a troca
- O que vc quer fazer nas páginas internas? quais páginas serão e teremos conteúdo para eu ter ideia?

**Comment by sousajul** [comment]
@marcioalvessilva está ok os ajustes realizados, te mandei por email o levantamento que fizemos das BVS temáticas para as páginas internas.

**Comment by sousajul** [comment]
@marcioalvessilva seguem as imagens da BVS Bolívia: 

https://drive.google.com/drive/folders/1xq2kqL0zQri_hpwjbJX1CV3kAG7Rux1Q

**Comment by marcioalvessilva** [comment]
Imagens atualizadas, por favor validar!

**Comment by sousajul** [comment]
Validado.
