### ISSUE TITLE
Imagem com nome de multimedia está impedindo do plugin de multimedia ser acessado (SMS.SP)

### ISSUE THREAD

**Issue by marcoslmori** [bireme/wordpress-themes#125]
Por favor, analisar se dentro da instância sms.sp.bvs.br não tem alguma imagem com o nome de multimedia que esta pedindo do plugim mostrar os registros publicados

**Comment by marcioalvessilva** [comment]
Imagem substituída!

**Comment by marcoslmori** [comment]
Ok, obrigado e o plugin já está funcionado https://sms.sp.bvs.br/multimedia/
