### ISSUE TITLE
PortalBVS

### ISSUE THREAD

**Issue by sousajul** [bireme/wordpress-themes#127]
Seguem observações:

Home

1. Falta Menu
2. Falta carrossel de destaques
3. Ao fazer uma busca aparece a seguinte msg "As informações que você está prestes a enviar não são seguras"
4. O RSS do direve na coluna "Acontece" não é o mesmo que está na produção, está remetendo para notícias 
5. O texto do rodapé de termos de uso ficou alinhado para a esquerda
6. Os Links para o LIS e Recursos Multimídia, não abrem na coluna "Produção da Rede"
7. Página da FAQ quebrou, está apresentando vários códigos

Subportal - Modelo BVS

1. Onde estamos usando o plugin de abre e fecha (persianas) quebrou e aparece um código, ex: http://red.bvsalud.org/modelo-bvs/pt/como-participar/
2. Quebrou a página https://red.teste.bvsalud.org/modelo-bvs/pt/instrumento-de-maturidade-da-bvs/. Na interface ingles não aparece o código, simplesmente sumiu o conteúdo.

**Comment by wilsonmoura** [comment]
@sousajul @marcoslmori ajustes realizados. Favor validar.

**Comment by marcoslmori** [comment]
@marcioalvessilva o plugin de acessibilidade está instalado, pode dar um revisada na css da instancia.  Obrigado

**Comment by sousajul** [comment]
- Segunda validação feita, e ok para os apontamentos.
Apenas observei que a opção de buscar em "Neste portal" está remetendo para o iahx ao invés de abrir resultados no portal.

**Comment by wilsonmoura** [comment]
Ajustes realizados conforme solicitado.
