### ISSUE TITLE
Configurar Rodapé dos plugins da BVS SMS-SP

### ISSUE THREAD

**Issue by sousajul** [bireme/wordpress-themes#129]
Configurar os plugins da BVS SMS-SP para apresentar o Rodapé igual da BVS Principal

https://sms.sp.bvs.br/lis/
https://sms.sp.bvs.br/direve/
https://sms.sp.bvs.br/multimedia/ 

Origem: https://github.com/bireme/wordpress-themes/issues/123

**Comment by marcioalvessilva** [comment]
Bom dia!
Footer inserido por favor validar!

**Comment by sousajul** [comment]
Validado.
