### ISSUE TITLE
Colapsar campos

### ISSUE THREAD

**Issue by pintoros** [bireme/wordpress-themes#13]
Solicito colapsar (como default) os seguintes campos de dados do repositório:
General Search Filters
Search Strategy II
Search Strategy III

**Comment by wilsonmoura** [comment]
@pintoros Conforme conversamos, esse ajuste não é possível, pois o plugin usado para criar os campos customizados não disponibiliza nenhuma configuração desse tipo. No entanto, ao colapsar ou expandir um grupo de campos, o mesmo permanecerá assim em todos os outros conteúdos.
