### ISSUE TITLE
Configurar RSS BVS Bolivia

### ISSUE THREAD

**Issue by sousajul** [bireme/wordpress-themes#130]
Favor configurar o RSS de "Documentos Recientes e Eventos" da BVS Bolivia https://bolivia.teste.bvsalud.org/.

- Incluir espaçamento
- Retirar duplicidade de título
- Incluir link do resultado nos títulos também ao clicar

![image](https://user-images.githubusercontent.com/13439949/185202814-6a4cdc39-f8c0-4100-b8c9-979f01beb84b.png)

**Comment by marcioalvessilva** [comment]
Realizado, por favor validar!

**Comment by sousajul** [comment]
Validado. Muito obrigada.
