### ISSUE TITLE
Verificar comportamento estranho do editor Gutemberg no portal da Rede BVS

### ISSUE THREAD

**Issue by sousajul** [bireme/wordpress-themes#134]
- Formulários sobrepostos
- Pagina fica mexendo sozinha, tremendo (kkkk)

![image](https://user-images.githubusercontent.com/13439949/186720373-30611cfc-041a-4b59-9a8c-96a2c0f31e45.png)

**Comment by wilsonmoura** [comment]
@sousajul conforme conversamos, foi identificado um conflito do editor Gutemberg com o plugin ShowHide Text Widget. Esse plugin serve pra ativar um widget com o comportamento de sanfona (collapse). Para evitar perda de conteúdo em outras páginas do site, a sugestão para resolução desse problema é ativar o editor clássico do WordPress.

**Comment by wilsonmoura** [comment]
@sousajul identificamos um conflito do editor Gutemberg com o plugin ShowHide Text Widget que está causando esse bug. Esse plugin serve pra ativar um widget com o efeito de sanfona (collapse). Para evitar a perda de conteúdo em outras páginas do site, a sugestão para resolução desse problema é ativar o editor clássico do WordPress.

**Comment by sousajul** [comment]
Após conversa com @marcoslmori e @marcioalvessilva foi acordado instalar o editor clássico do WordPress. Aberto chamado para instalação do plugin - chamado N.º 8731
