### ISSUE TITLE
Texto descritivo nas imagens e conteúdos do portal

### ISSUE THREAD

**Issue by sousajul** [bireme/wordpress-themes#135]
Verificar nas imagens e conteúdos do portal a possibilidade de ao passar o mouse abrir uma caixa com um texto descritivo.

Precisamos implementar isso na BVS SMS-SP e BVS Hanseníase.

**Comment by marcioalvessilva** [comment]
Depois de uma analise considero que não temos como inserir tooltips nesses projetos (BVS SMS e BVAS Hanseníase), os plugins não são compatíveis. Para os próximos temas vou analisar a possibilidade de inserir diretamente no tema, através de bibliotecas jquery.
Como não requer ação vou fechar o issue, caso encontre solução no futuro podemos criar nosso issue.
