### ISSUE TITLE
Ajuste layout BVS Hansen + barra de acessibilidade

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/wordpress-themes#139]
https://hansen.teste.bvs.br/

![image](https://user-images.githubusercontent.com/48724136/193659638-c7f7f666-7abf-48f6-82c5-5cb684cab894.png)

**Comment by marcioalvessilva** [comment]
Validar

https://hansen.teste.bvs.br/
![image](https://user-images.githubusercontent.com/48724136/198054719-cb51e0a2-5834-4c14-a73c-b3b85b7d54ed.png)

**Comment by marcoslmori** [comment]
Solicitado para a @sousajul validar

**Comment by marcoslmori** [comment]
@sousajul validou confirmou via whats que pode colocar em produção

**Comment by marcioalvessilva** [comment]
Grato @marcoslmori, vou finalizar o issue, qualquer coisa por favor reabrir ou iniciar outro.
