### ISSUE TITLE
Ajuste na Vitrine da BVS ECOS 

### ISSUE THREAD

**Issue by marcoslmori** [bireme/wordpress-themes#140]
@marcioalvessilva , verificar a possibilidade de realizar o seguinte ajuste na Vitrine da BVS ECOS (https://economia.saude.bvs.br/vitrinas/post_vitrines/):

- O link no canto inferior direito "Coleção de Vitrines do Conhecimento da Rede BVS" alterar o texto para: "Coleção de Vitrines do Conhecimento BVS ECOS" e incluir o link: https://bvsalud.org/lis-vitrinas?filter=descriptor:%22Economia%20da%20Sa%C3%BAde%22. Se não for possível fazer essa alteração, por favor, retirar o link.

Recebido do chamado 7608:  a
http://suporte.bvs.br//ocomon/geral/ticket_show.php?numero=7608&id=801621634920213621324097260

**Comment by marcioalvessilva** [comment]
Não foi possível fazer alteração do conteúdo, então o link foi removido.

**Comment by marcioalvessilva** [comment]
Finalizado!
