### ISSUE TITLE
Verificar o plugin de acessibilidade instalada nas BVS e portais

### ISSUE THREAD

**Issue by sousajul** [bireme/wordpress-themes#141]
No portal Evipnet (https://brasil.evipnet.org/) na barra de acessibilidade ao clicar nos ícones "aumentar as fontes e Alto contraste" o recurso é aplicado, mas ele muda para a página "Serviços Colaborativos"

![image](https://user-images.githubusercontent.com/13439949/194334915-93d28059-7b0b-4162-a05b-e89d5c2653e0.png)

O item "Rodapé" da BVS SMS-SP não remete para o footer.

**Comment by marcioalvessilva** [comment]
Ajuste realizado
Foi encontrado outro problema nos link (conteúdo principal e pesquisa).
Vou manter esse issue aberto para verificar dentro do plugin quais as chances de ajuste ou como ultima opção oculta o link

**Comment by marcioalvessilva** [comment]
Ajuste realizado no BVS-SMS
Ajuste EvipNet
 - Atalho de busca removido, plugin não vai funcionar para esse tipo de busca
 - Foi feito ajuste para largura acompanhar o contêiner do portal.

**Comment by sousajul** [comment]
Validado.
