### ISSUE TITLE
Ajustes no Layout da BVS Mocambique em instancia de teste

### ISSUE THREAD

**Issue by marcoslmori** [bireme/wordpress-themes#146]
itens: 
Configurar a caixa de pesquisa para buscar no plugin bibliographic e tirar as opções abaixo da caixa de busca "formulário e como pesquisar"
Ajustar o layout no plugin bibliographic quando acessa o registro
Ajustar filtros no plugin bibliographic

**Comment by marcoslmori** [comment]
Ajustar também o plugin de acessibilidade

"Configurar a caixa de pesquisa para buscar no plugin bibliographic e tirar as opções abaixo da caixa de busca "formulário e como pesquisar" - feito

**Comment by marcioalvessilva** [comment]
Validar - Itens
Obs: barra de acessibilidade precisa consultar o @wilsonmoura pois não aparece na inspeção de elementos

**Comment by wilsonmoura** [comment]
@marcoslmori @marcioalvessilva para exibir a barra de acessibilidade corretamente, é necessário que o template `header.php` do tema esteja executando o hook `wp_body_open` logo após a tag `<body>`. Veja exemplo:

    <body>
        <?php wp_body_open(); ?>

Vale ressaltar que os temas mais recentes do WordPress (desde a versão 5.2.0) já possuem essa característica por padrão. Sendo assim, os temas desenvolvidos devem seguir esse mesmo padrão.

Para mais informações, segue link do site oficial do WordPress com a documentação do hook `wp_body_open`: https://developer.wordpress.org/reference/functions/wp_body_open/

**Comment by marcioalvessilva** [comment]
Bom dia Mori @marcoslmori, fiz a alterações.
Por favor atualizar tema e validar com o git hub.

**Comment by marcioalvessilva** [comment]
Finalizado!
