### ISSUE TITLE
Centralizar o texto Red BVS Enfermería no rodapé da BVS Enfermagem e criar duas imagens para os banner da BVS conforme textos abaixo:

### ISSUE THREAD

**Issue by barrosjo** [bireme/wordpress-themes#148]
Banner em pt:
Biblioteca Virtual em Saúde
Enfermagem

Banner em es:
Biblioteca Virtual en Salud 
Enfermería

https://bvsenfermeria.bvsalud.org/

**Comment by marcioalvessilva** [comment]
Finalizado!
