### ISSUE TITLE
BVS Regional - Como pesquisar

### ISSUE THREAD

**Issue by pintoros** [bireme/wordpress-themes#150]
Seguem as demandas especificadas em reunião do dia 03/11/2022 quanto a necessidade para disponibilizar material didático para usuários da BVS.
Os tipos de material são:
1) Vídeos curtos que já contam com playlists por idioma no youtube (1 link para cada idioma - ex: https://youtube.com/playlist?list=PLIPBIT9lmQuLh1P5wH5r7YwlSShf9WV1a )
2) Link para página explicativa de acesso ao curso a online de pesquisa na BVS (infelizmente o acesso pelo Campus virtual não é intuitivo, por isso precisamos explicar a forma de acessar para que o usuário chegue ao curso)
3) Página em html com tutorial, guia navegáveis e acesso ao pdf (Scorm) compartilhado via sharepoint. 
4) Serviço Pergunte ao bibliotecário (implementado na página atual - https://bvsalud.org/como-pesquisar ) 

*Link de acesso ao conteúdo html que precisa ser baixado no nosso servidor: 

[https://bireme-oms-tuto-intera-aces-port-bvs-pt.webflow.io/](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbireme-oms-tuto-intera-aces-port-bvs-pt.webflow.io%2F&data=05%7C01%7Cpintoros%40paho.org%7Cb9015f561647451dbf7208dabdc3fad3%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638030946676312707%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CZA3pBw2FVTrhgAPRSwOaWJ79G69rK19rBh0fuvyRrk%3D&reserved=0)

[https://drive.google.com/drive/folders/1VwojWfmksp4VLfq0phxOfyLE3rHzslRK](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdrive.google.com%2Fdrive%2Ffolders%2F1VwojWfmksp4VLfq0phxOfyLE3rHzslRK&data=05%7C01%7Cpintoros%40paho.org%7Cb9015f561647451dbf7208dabdc3fad3%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638030946676312707%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vvGAVJFIfuEs5c6GxCYn61qBtv0xRPwDnRvCtsLatHk%3D&reserved=0)

Segue uma sugestão da @Lizbiruel 
<img width="820" alt="Como pesquisa_modelo" src="https://user-images.githubusercontent.com/29313904/200607800-de45eafa-bf6e-47ec-88ef-d06b22a60983.png">

**Comment by marcioalvessilva** [comment]
Boa tarde @pintoros , em nossa reunião você ficou de enviar uma sugestão de nome para essa URL, aguardo!

**Comment by pintoros** [comment]
/searchtutorial

Obrigada


Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:2210a728-bed1-404b-8bae-89c3b2bf4f6b]

________________________________
De: Márcio Alves ***@***.***>
Enviado: quarta-feira, 9 de novembro de 2022 12:51
Para: bireme/wordpress-themes ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/wordpress-themes] BVS Regional - Como pesquisar (Issue #150)


Boa tarde @pintoros<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpintoros&data=05%7C01%7Cpintoros%40paho.org%7C3cabcdf4093947d19f4e08dac26a46a8%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638036058953435064%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QJcSJfUZwe1k3Fyf6P3GQ7%2FDIuCvKDB6gWafhUOUhu4%3D&reserved=0> , em nossa reunião você ficou de enviar uma sugestão de nome para essa URL, aguardo!

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fwordpress-themes%2Fissues%2F150%23issuecomment-1308967778&data=05%7C01%7Cpintoros%40paho.org%7C3cabcdf4093947d19f4e08dac26a46a8%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638036058953435064%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PPkBDyKUi32Ma%2FNUiqxCjv9%2B8KW6nZkYrQbJmoP98f0%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4DW4RT2HWQGX553JR3WHPCAJANCNFSM6AAAAAAR2OYS2I&data=05%7C01%7Cpintoros%40paho.org%7C3cabcdf4093947d19f4e08dac26a46a8%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638036058953435064%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vYM5EW94vmslkhgwM9h84PNxfgaSq006Rw89S9cUZKI%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by marcoslmori** [comment]
Publicado em teste, validar https://teste.bvsalud.org/searchtutorial/

**Comment by pintoros** [comment]
Validado Márcio! 

Seguem os links para o menu:

Curso online de busca na BVS - https://mooc.campusvirtualsp.org/course/view.php?id=386
Online course of searching on VHL - https://mooc.campusvirtualsp.org/course/view.php?id=391
Curso online de búsqueda en la BVS - https://mooc.campusvirtualsp.org/course/view.php?id=388
Cours en ligne de recherche sur le BVS - https://mooc.campusvirtualsp.org/course/view.php?id=392

(incluir link de acordo com idioma)
Tutorial e guia de pesquisa  
Tutorial y guía de búsqueda
Tutorial and search guide
Tutoriel et guide de recherche 

@Lizbiruel vai passar os links
Guia rápido em vídeo
Videoguía rápida
Quick video guide
Petit guide vidéo

Pergunte ao bibliotecário - https://bvsalud.org/contate-nos/
Pregunte al bibliotecario - https://bvsalud.org/es/contactenos/
Ask a librarian - https://bvsalud.org/en/contact_us/
Demander au bibliothécaire - não tem

**Comment by marcioalvessilva** [comment]
Olá Márcio,

Segue os links atualizados para a página da Home do Portal da BVS - Como pesquisar?

Versões:  

Acesso e Uso da Informação Científica em Saúde
Português - https://bit.ly/CVOPAS-Acesso-Informacao-POR

Access and Use of Scientific Information in Health
Inglês - https://bit.ly/PAHOVC-ScientificInformationinHealth

Acceso y uso de la información científica en salud
Espanhol - https://bit.ly/CVOPS-InformacionCientificaEnSalud

L'Accès et L'Utilisation de l'Information Scientifique en Santé
Francês - https://bit.ly/CVOPS-CartedesPreuves

______________________________________________
Evidence Map: methodology and application
https://bit.ly/PAHOVC-EvidenceMap
 
Mapa de Evidencias: Metodología y aplicación
https://bit.ly/CVOPS-MapadeEvidencias

Mapa de Evidências: metodologia e aplicação
https://bit.ly/CVOPAS-MapaEvidMetAplicPOR

Carte des Preuves: méthodologie et application
https://bit.ly/CVOPS-CartedesPreuves

**Comment by marcioalvessilva** [comment]
Por favor validar página Guia rápido em vídeo em português (precisa fazer login para visualizar)
https://bvsalud.org/?page_id=8774&preview=true

**Comment by pintoros** [comment]
Boa tarde Márcio, o link não permite a visualização. Aparece como na imagem e ao clicar em Como pesquisar vai para página atual.
![image](https://user-images.githubusercontent.com/29313904/209563172-81ae9aa0-f422-4fb5-9f0c-3d736f65eda3.png)

**Comment by marcioalvessilva** [comment]
Eu comentei que precisava fazer login, segue print
![image](https://user-images.githubusercontent.com/48724136/209568804-3b25b559-e8e7-4c59-acd7-57edc0064a19.png)

**Comment by pintoros** [comment]
Desculpa Márcio, não percebi.

Ficou ótimo!

Obrigada!



Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:4f071298-effb-4709-ae88-2a17cabad53a]

________________________________
De: Márcio Alves ***@***.***>
Enviado: segunda-feira, 26 de dezembro de 2022 13:46
Para: bireme/wordpress-themes ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/wordpress-themes] BVS Regional - Como pesquisar (Issue #150)


Eu comentei que precisava fazer login, segue print
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F48724136%2F209568804-3b25b559-e8e7-4c59-acd7-57edc0064a19.png&data=05%7C01%7Cpintoros%40paho.org%7Ce15dae38322e420edd9608dae760c12d%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638076699999929357%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oQOf5GhvFr5%2FmQvQ8cKonpb8npW1cTF5bQV9Zubi1uQ%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fwordpress-themes%2Fissues%2F150%23issuecomment-1365281382&data=05%7C01%7Cpintoros%40paho.org%7Ce15dae38322e420edd9608dae760c12d%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638076699999929357%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dSkeZA3Y3HGmSrwqOOaXwrl2dxM9PGaV6AzmjjmRx00%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4BV5BSKGIDEZDE4RULWPHDWZANCNFSM6AAAAAAR2OYS2I&data=05%7C01%7Cpintoros%40paho.org%7Ce15dae38322e420edd9608dae760c12d%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638076699999929357%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=I15OYhcQtTSpYZuFrZ8FloUsH6ct54PJjJj4GgVwh%2FE%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by marcioalvessilva** [comment]
@pintoros por favor enviar arquivos do tutorial em vídeo para ser publicado pelo ITI e me passar a URL, fico no aguardo e continuo à disposição.
Abraço!

**Comment by pintoros** [comment]
Márcio,  a Beth pediu uma atuallização para empresa no html. Vamos aguardar para enviar ao ITI, enquanto isso manteremos a página provisória que está hoje.
Obrigada

**Comment by pintoros** [comment]
Bom dia @marcioalvessilva , de acordo com o chamado OVOMON #9062, já estão disponíveis no servidor o material em necessário para construir essa aplicação.
Obrigada

**Comment by marcioalvessilva** [comment]
Ok @pintoros, vou dar continuidade e chamo assim que surgirem as dúvidas.

**Comment by pintoros** [comment]
Segue a ordem do Menu:

Curso online de pesquisa 
Tutorial e guia de pesquisa
 -Download do tutorial
 -Download do guia
Guia rápido em vídeo
Pergunte ao bibliotecário


Online search course
Tutorial and search guide
  -Download the tutorial
  -Download the guide
Quick video guide
Ask a librarian


Curso online de búsqueda 
Tutorial y guía de búsqueda
  -Descargar el tutorial
  -Descargar la guía
Videoguía rápida
Pregunte al bibliotecario

**Comment by pintoros** [comment]
Incluir na página anterior:
@marcioalvessilva se puder embutir o link do Portal Regional, melhor, aí o usuário clica e vai direto para a página.

- Página desatualizada! Acesse o novo menu **Como pesquisar?** no Portal Regional da BVS - https://bvsalud.org/
- Page out of date! Access the new menu **How to search?** on the VHL Regional Portal - https://bvsalud.org/en/
- ¡Pagina desactualizada! Acceder al nuevo menú ¿Cómo buscar? en el Portal Regional de la BVS - https://bvsalud.org/es/

**Comment by marcioalvessilva** [comment]
Concluído!!!
