### ISSUE TITLE
Criação de página template para uso em eventos

### ISSUE THREAD

**Issue by pintoros** [bireme/wordpress-themes#152]
Solicito a criação de uma página template nos moldes da que foi criada para https://bvsalud.org/hsr2022 para que possamos utilizar nos eventos em que a BIREME faz a promoção de produtos e serviços. Iniciar pelo PT devido a demanda de evento no Brasil (https://saudecoletiva.org.br/index.php#topo) 

URL padrão   
https://bvsalud.org/events - gerar QR Code

Conteúdo Customizável  
- selo do evento no Header
- banner no Footer - será usada a mesma arte para o destaque do Portal Regional

Segue anexo conteúdo que será alterado minimamente para os futuros eventos
[Conteudo pagina eventos - Abrasco.docx](https://github.com/bireme/wordpress-themes/files/9974162/Conteudo.pagina.eventos.-.Abrasco.docx)

**Comment by marcioalvessilva** [comment]
@pintoros segue primeira versão, aguardo acompanhamento - http://mockups.teste.bireme.org/eventos/

**Comment by pintoros** [comment]
Márcio, pra mim OK!
Só faltou repetir a frase:
OPAS BRASIL e BIREME no ABRASCÃO 2022 no banner do footer. A mesma arte para eu aproveitar no destaque do Portal Regional e gerar o QR Code.

Obrigada


Rosemeire Rocha Pinto
Supervisora Serviço de Capacitação e Atenção ao Usuário. Serviços Cooperativos de Informação-SCI

BIREME/OPAS/OMS<https://www.paho.org/bireme/index.php?lang=pt> | Tel +55 11 5576-9833 VOIP 44839

[cid:7699d813-3e60-4045-a79f-1a466e5b4262]

________________________________
De: Márcio Alves ***@***.***>
Enviado: quinta-feira, 10 de novembro de 2022 14:32
Para: bireme/wordpress-themes ***@***.***>
Cc: Pinto, Rosemeire (BIR) ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/wordpress-themes] Criação de página template para uso em eventos (Issue #152)


@pintoros<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpintoros&data=05%7C01%7Cpintoros%40paho.org%7C09660a80d582416133df08dac3417d4b%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638036983284072925%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZRvGnQCKHDMOlRa1KY%2F2ffly2WcjFZxAwXgQuCuXpTc%3D&reserved=0> segue primeira versão, aguardo acompanhamento - http://mockups.teste.bireme.org/eventos/<https://nam12.safelinks.protection.outlook.com/?url=http%3A%2F%2Fmockups.teste.bireme.org%2Feventos%2F&data=05%7C01%7Cpintoros%40paho.org%7C09660a80d582416133df08dac3417d4b%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638036983284072925%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MmNW1kTIDc59G9SgncDbHMqpU1o6uyMiVHiLMSLCDYA%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fwordpress-themes%2Fissues%2F152%23issuecomment-1310646844&data=05%7C01%7Cpintoros%40paho.org%7C09660a80d582416133df08dac3417d4b%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638036983284072925%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jK7qsIgGzcoxcO%2Fcv7aeZfTq6teAy%2B8p6cmorf5%2B80s%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAG7UW4BBTIJD3BLGQZO5J2DWHUWRLANCNFSM6AAAAAAR3XVQDI&data=05%7C01%7Cpintoros%40paho.org%7C09660a80d582416133df08dac3417d4b%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C638036983284072925%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2kQtIAey6vHFAN2jgHMkeUYGONNK5NVaWcSy%2FMLPLGo%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.

**Comment by marcioalvessilva** [comment]
Banner Portal Regional
https://github.com/bireme/artes-graficas/tree/main/banners-sites/regional/abrascao/JPG

QR Code - Endereço reservado pagina não publicada ate o momento.
![qr code bvs eventos](https://user-images.githubusercontent.com/48724136/202249870-74b057bb-6c3f-44e5-acc5-75fdc713d0a4.jpg)

**Comment by pintoros** [comment]
Aprovado o banner Márcio!

Pode incluir o QR code na página? Pode ser no top ou na imagem logo abaixo em que está a frase de chamada Construindo sistemas de saúde...

E já publicar a página na sequência.

Obrigada

**Comment by marcioalvessilva** [comment]
Publicado - https://bvsalud.org/events/
por favor validar e fechar

**Comment by pintoros** [comment]
Márcio, só faltou incluir o QR code na página. 
Feito isso pode encerrar, muito obrigada.

**Comment by marcioalvessilva** [comment]
Finalizado!
