### ISSUE TITLE
Ajuste da CSS do DocPress Guias e Manuais LILACS

### ISSUE THREAD

**Issue by suelisuga** [bireme/wordpress-themes#155]
Prezados,

Solicito ajuste da CSS do site de Guias e Manuais da LILACS
Formatação:
![image](https://user-images.githubusercontent.com/13105683/202504409-b52da72e-0532-4002-a84d-c69d9bdfc726.png)
Página publicada:
![image](https://user-images.githubusercontent.com/13105683/202504476-89ac5a26-1f2e-4e03-9c69-b84e0cc359ce.png)

O resultado é desproporcional e temos utilizado mais o título 2 e 4 pois o título 1 é igual ao do título da página.
Exemplo:
![image](https://user-images.githubusercontent.com/13105683/202504820-2464a23a-9ac9-4ca2-81c0-2b5f4e5391bd.png)

Obrigada!

**Comment by suelisuga** [comment]
@marcioalvessilva link dos guias e manuais: https://lilacs.bvsalud.org/guias-e-manuais/

Obrigada

**Comment by suelisuga** [comment]
@marcioalvessilva poderia verificar se é possível aplicar da seguinte maneira?

► FORMATAÇÃO:
Fonte - título, subtítulo, texto, legenda, fonte
Título capítulo: Roboto Medium 24pt espaçamento 28pt 
Nome autores: Roboto Medium 16pt espaçamento 22pt
Link orcid: Roboto regular 12 pt espaçamento 20pt 
Afiliação: Roboto light 12 pt espaçamento  16pt
legenda: Roboto regular 10pt espaçamento 22pt
Corpo do texto
parágrafo: Roboto light 12pt 20pt 
parágrafo: quadro: Roboto light 12 pt espaçamento 18pt
parágrafo referências Roboto 11pt espaçamento 17pt
hierarquia de títulos 
T1 Roboto medium 18pt espaçamento 20pt
T2 Roboto medium 16pt espaçamento 20pt 
T3 Roboto medium 15pt espaçamento 20pt
T4 Roboto medium 14pt espaçamento 20pt
Títulos das ilustrações: Roboto bold 12pt espaçamento 18pt


Cor: 
RGB: 0 157 224 #009ce0 
Títulos RGB: 4 104 191 #0468bf


Fico à disposição.

Obrigada

**Comment by suelisuga** [comment]
@marcioalvessilva enviei modelo pelo email.

Obrigada

**Comment by suelisuga** [comment]
@marcioalvessilva 
![image](https://user-images.githubusercontent.com/13105683/206707991-00330be9-9cb5-4ba7-b9c6-681ef0bd2b7c.png)
Uma dúvida, o título 2 não deveria ser maior que o título 3?

**Comment by suelisuga** [comment]
@marcioalvessilva na página inicial, não sei como está configurado pq não aparece para usuário, mas seria possível deixar esteticamente mais destacado o título do manual/guia?

![image](https://user-images.githubusercontent.com/13105683/206710505-ba750cf0-51f9-4702-bd9c-8af4757e13f0.png)

Achei um pouco apagada a cor...
Obrigada

**Comment by suelisuga** [comment]
Solicito aumentar um pouco a fonte de parágrafos para melhorar legibilidade.

![image](https://user-images.githubusercontent.com/13105683/206713373-fed9c8a9-9166-4e95-821b-19dd80b275e7.png)

**Comment by suelisuga** [comment]
@marcioalvessilva tamanho da fonte muda sem eu ter feito na interface administrativa

![image](https://user-images.githubusercontent.com/13105683/206735613-ce3d1b1a-e6fd-4150-ac43-9116a53e5ee7.png)

![image](https://user-images.githubusercontent.com/13105683/206735733-939a86a8-79c0-4108-8ba8-fd91868e5217.png)

**Comment by marcioalvessilva** [comment]
**Ajustes**
Título 1: 23pt;
Título 2: 20pt;
Título 3: 18pt;
Paragrafo: 13pt;
Listas: 13pt;
Sobre a cor foi a mesma usada no PDF (fiz ajuste) aguardo novos pontos

**Comment by marcioalvessilva** [comment]
Finalizado, continuo à disposição, para futuros ajustes.

**Comment by suelisuga** [comment]
@marcioalvessilva a Angélica revisou e encontrou algumas melhorias necessárias.

Poderia revisar?

https://lilacs.bvsalud.org/guias-e-manuais/docs/guia-de-boas-praticas-para-periodicos-lilacs-2/gestao-de-periodicos-cientificos-etapas-acoes-e-participantes-dos-processos-editoriais/


- Aumentar espaçamento entre parágrafos.
- Diminuir fonte dos números sobrescritos.
- Na visualização, fonte do item "1. Introdução" está diferente das demais, apesar de estarem todos como <Título 2>.
- A "Tabela 1" aparece corretamente na edição, mas na página publicada, ela deixa de estar centralizada e o texto da legenda sobrepõe a última linha.
- Há a possibilidade de uma fonte menor que a do <Parágrafo>, para utilizarmos nas legendas das figuras e tabelas?
- Tem como deixar o <Título 4> um pouco maior que <Parágrafo>. Precisamos utilizá-lo, mas o tamanho da fonte é menor e fica desproporcional para indicar um título.
- Coloquei um ícone ao final de cada referência para voltar ao texto. Existe uma melhor opção delink, que fique mais discreto?

https://lilacs.bvsalud.org/guias-e-manuais/docs/guia-de-boas-praticas-para-periodicos-lilacs-2/gestao-de-periodicos-cientificos-etapas-acoes-e-participantes-dos-processos-editoriais/a-autora/

- Na página sobre a autora, na visualização o nome vem logo abaixo da foto, mas na página publicada, há um espaço grande entre eles.

**Comment by marcioalvessilva** [comment]
- Aumentar espaçamento entre parágrafos. (foi inserido um espaçamentos entre parágrafos - também foi criado uma classe para ajusta a exceções)
**Solução: inserir classe m-b1 nos parágrafos que não podem ter o espaçamento<p _class="m-b1"_ >**

- Diminuir fonte dos números sobrescritos.
**Feito**

- Na visualização, fonte do item "1. Introdução" está diferente das demais, apesar de estarem todos como <Título 2>.
**Foi removido bold do titulo**

- A "Tabela 1" aparece corretamente na edição, mas na página publicada, ela deixa de estar centralizada e o texto da legenda sobrepõe a última linha.
**Foi inserido um style "margin:auto"** esse recurso centraliza elementos com tamanho definido 
**`<table style="height: 786px; margin:auto;" width="538" align="center">`**

- Há a possibilidade de uma fonte menor que a do <Parágrafo>, para utilizarmos nas legendas das figuras e tabelas?
**Solução: inserir classe captionT nos parágrafos desejados**
**`<p  class="captionT">texto</p>`**


- Na página sobre a autora, na visualização o nome vem logo abaixo da foto, mas na página publicada, há um espaço grande entre eles
**Foi encontrado titulos sem textos em baixo da foto conforma print (já foram removidos e espaço não existe mais)**
![image](https://user-images.githubusercontent.com/48724136/232887782-46f3c04f-e3ac-489d-871f-96eb06f4810c.png)

Demais itens ainda estão sendo solucionados.

**Comment by marcioalvessilva** [comment]
- Tem como deixar o <Título 4> um pouco maior que <Parágrafo>. Precisamos utilizá-lo, mas o tamanho da fonte é menor e fica desproporcional para indicar um título.
![image](https://user-images.githubusercontent.com/48724136/232901926-cbc42b87-70a8-4969-8778-db9919c3f16d.png)
**Os tamanhos estão declarados assim:**
H1 - font-size:23pt;
H2 - font-size:20pt;
H3 - font-size:18pt;
H4 - font-size:16pt;
H5 -	font-size:13pt;
P - font-size:13pt;

**Comment by marcioalvessilva** [comment]
- Coloquei um ícone ao final de cada referência para voltar ao texto. Existe uma melhor opção delink, que fique mais discreto?

**Imagem em jpg**
![1f53c](https://user-images.githubusercontent.com/48724136/233453546-d66fa986-7633-4abe-a7ed-63985ffdbc0a.jpg)

**Imagem em png**
![1f53c](https://user-images.githubusercontent.com/48724136/233453548-6840f75f-afdc-42dc-97c3-50cdac3cb7bc.png)

**Imagem em svg**
![1f53c](https://user-images.githubusercontent.com/48724136/233453550-fc30e778-a1cd-4a0e-9498-bb59c30f48d8.svg)

Acredito que tenha atendido dos as modificações solicitadas

**Comment by AngelicaSAPaula** [comment]
Muito obrigada!
