### ISSUE TITLE
Ajustar a cor dos links visitados na instancia de vitrinas da BVS SES.SP

### ISSUE THREAD

**Issue by marcoslmori** [bireme/wordpress-themes#156]
https://ses.sp.teste.bvs.br/vitrinas/post_vitrines/inovacao-em-saude-na-ses-sp/

![image](https://user-images.githubusercontent.com/10047460/203328250-2e22528f-f214-4d51-ad13-d0712dd2dd08.png)

**Comment by marcioalvessilva** [comment]
Validar!

**Comment by marcoslmori** [comment]
Informado para a cliente validar

**Comment by marcioalvessilva** [comment]
Concluído!
