### ISSUE TITLE
Ajustar o template das páginas secundarias do portal CNS

### ISSUE THREAD

**Issue by sousajul** [bireme/wordpress-themes#157]
Ex: https://cns.teste.bvs.br/resolucoes-recomendacoes-e-mocoes/

Ajustar para todas as páginas secundárias.

**Comment by marcioalvessilva** [comment]
@sousajul 
É necessário fazer configurações na criação das páginas

### **1 - Configurar se a página terá widget-aside (ao lado)**
![image](https://user-images.githubusercontent.com/48724136/203882754-40a9e871-0d83-4e00-a193-f6f2e5c65995.png)


### **2 - Definir o tipo de container**

![image](https://user-images.githubusercontent.com/48724136/203882878-4e319a2a-0a83-4f87-a96a-4c0ce8dc6af3.png)


### **Exemplo - Boxed**
![image](https://user-images.githubusercontent.com/48724136/203882718-ae870527-4960-4b2d-bb5f-cdc416ee2aa7.png)



### **Exemplo - Full Width / Contained**
![image](https://user-images.githubusercontent.com/48724136/203883089-1ec61703-4b73-4f2a-97a2-e88205d904b5.png)



### **Exemplo  - Full Width / Stretched**
![image](https://user-images.githubusercontent.com/48724136/203883262-7328c972-b632-43ef-a334-fde07d89d93f.png)

Fico à disposição para explicar

**Comment by sousajul** [comment]
Ok @marcioalvessilva entendi como ajustar. Fiz uns testes agora e está tudo certinho.

Obrigada.
