### ISSUE TITLE
Apoio para configurar a caixa de busca do portal CNS (Chamado 8892)

### ISSUE THREAD

**Issue by marcoslmori** [bireme/wordpress-themes#159]
Apoio para configurar a caixa de busca do portal CNS.

Manter como opções de busca no "buscar em":

- Base CNS: https://pesquisa.bvsalud.org/cns-br/
- Atos Normativos: https://cns.teste.bvs.br/leisref

Por favor, colocar o código html para futuras customizações

**Comment by marcioalvessilva** [comment]
@marcoslmori por favor valider

segue código utilizado

<div class="multisearch">
    <form action="https://pesquisa.bvsalud.org/cns-br/" method="get" id="searchForm" class="vhl-search-form">
        <input type="hidden" name="lang" value="pt">
        <input type="hidden" name="home_url" value=https://pesquisa.bvsalud.org/cns-br/>
        <input type="hidden" name="home_text" value="CNS">
        <input type="hidden" id="filter1" name="" value="BIREME">
        <label for="vhl-search-input" style="display: none;">Pesquisa</label>
        <input type="text" id="vhl-search-input" class="vhl-search-input" name="q" value="">
        <a href="javascript:void(0);" class="search-submit">
            <img src="/wp-content/uploads/2022/05/lupa-MA.png">
        </a>
    </form>
    <div class="searchItens">
        <span>Buscar em:</span>
        <input type="radio" name="engine" value="op1" id="search-op1" checked="checked"> <label for="search-op1">Base CNS:</label>
        <input type="radio" name="engine" value="op2" id="search-op2"> <label for="search-op2">Atos Normativos:</label>
    </div>
    <script>
        (function() {
            $ = jQuery;
            $(".search-submit").click(function () {
                $(this).closest("form").submit();
            });
            $("#search-op1").click(function () {
                $("#filter1").val('');
            });
            $("#search-op2").click(function () {
             $('#searchForm').attr('action', 'https://cns.teste.bvs.br/leisref');
         });
        })();
    </script>
</div>
<style>
    .vhl-search {
        width: 50%; margin: 4em auto 2em;
    }
    #vhl-search-input{
        width: 83%; height: 38px; border-color: #153d8a;
    }
    .search-submit img {
        height: 42px !important;
    }
    .vhl-search-submit {
        height: 42px !important;
    }
    .search-submit {
        vertical-align: bottom!important;
    }
    .vhl-search {
        width: 50%; margin: -1em auto 2em;
    }
    .multisearch {
        width: 50%; margin: 0px auto 0px; 
    }
</style

**Comment by sousajul** [comment]
@marcioalvessilva é possível colocar o item "atos normativos" mais afastado de Base CNS?

![image](https://user-images.githubusercontent.com/13439949/204906187-d66f673f-afb2-44d5-a875-d94ed8082378.png)

**Comment by marcioalvessilva** [comment]
Atualizado! por favor validar
![image](https://user-images.githubusercontent.com/48724136/205037724-53aad824-fbe3-4cb1-9db9-557f300aa88c.png)

**Comment by sousajul** [comment]
Validado.
