### ISSUE TITLE
Instalar plugin de acessibilidade portal CNS

### ISSUE THREAD

**Issue by sousajul** [bireme/wordpress-themes#160]
https://cns.teste.bvs.br/.

**Comment by marcioalvessilva** [comment]
Por favor validar!

![image](https://user-images.githubusercontent.com/48724136/205043716-d36b43bf-30e7-4d33-af7b-48925c71c91a.png)

**Comment by sousajul** [comment]
@marcioalvessilva o plugin de acessibilidade já não vem com os termos de uso e politicas de privacidade que geralmente fica no rodapé?

**Comment by marcioalvessilva** [comment]
Habilidade!

**Comment by sousajul** [comment]
Validado!
