### ISSUE TITLE
Instalar plugin de redes sociais no rodapé do Portal CNS

### ISSUE THREAD

**Issue by sousajul** [bireme/wordpress-themes#161]
Solicito apoio para configurar ícones de redes sociais no rodapé do Portal CNS 

Facebook  [fb.com/ConselhoNacionaldeSaude](http://fb.com/ConselhoNacionaldeSaude)
Twitter [twitter.com/comunicacns](http://twitter.com/comunicacns)
Instagram  [instagram.com/conselhonacionaldesaude.cns](http://instagram.com/conselhonacionaldesaude.cns)

**Comment by marcioalvessilva** [comment]
Por favor validar!

![image](https://user-images.githubusercontent.com/48724136/205045990-d1f8b479-dbed-46e6-a36e-4af2e449a2af.png)

**Comment by sousajul** [comment]
Validado.
