### ISSUE TITLE
Verificar tema Portal Evipnet Brasil

### ISSUE THREAD

**Issue by sousajul** [bireme/wordpress-themes#162]
Poderiam verificar o tema do portal do Evipnet, pois há alguns dias não está sendo possível editar o o portal para atualizações.
https://brasil.evipnet.org/.

![image](https://user-images.githubusercontent.com/13439949/206003578-fc8a7e36-6654-41c6-a4ea-3d4add2876f3.png)

**Comment by wilsonmoura** [comment]
Problema resolvido utilizando as orientações disponíveis na página abaixo:

https://elementor.com/help/elementor-widget-panel-not-loading/
