### ISSUE TITLE
Ajustar a cor de fundo do direve do portal da rede pois está gerando um contraste ruim com a cor dos eventos relacionado

### ISSUE THREAD

**Issue by barrosjo** [bireme/wordpress-themes#164]
Direve: https://red.bvsalud.org/eventos-rede-BVS/resource/?id=27550

Acho que pode seguir o padrão dos outros plugins que parece ok: https://red.bvsalud.org/lis-rede-BVS/resource/?id=48529 https://red.bvsalud.org/multimedia/resource/?id=multimedia.media.10021

![Portal da Rede BVS](https://user-images.githubusercontent.com/19578003/218486323-55f5d887-7668-40ad-9e4c-1027b09fca80.png)

**Comment by marcioalvessilva** [comment]
Por favor validar
![image](https://user-images.githubusercontent.com/48724136/218572732-49287d28-e7fd-4dd4-80ba-d76b14d77335.png)

**Comment by barrosjo** [comment]
Validado. Obrigada!
