### ISSUE TITLE
Criar menus com links para os idiomas nos sites dos guias e manuais, em pt, ingles e espanhol 

### ISSUE THREAD

**Issue by marcoslmori** [bireme/wordpress-themes#165]
guias e manuais: https://lilacs.bvsalud.org/guias-e-manuais/ (Produção)
guias-y-manuales: https://lilacs.teste.bvsalud.org/guias-y-manuales/ (Teste)
guias-y-manuales: https://lilacs.teste.bvsalud.org/guias-y-manuales/ (Teste)

**Comment by marcioalvessilva** [comment]
@wilsonmoura conforme apresentado é necessário criar área para menu/widget dentro do **tema** de forma que seja multiplicado nas demais instâncias 
![image](https://user-images.githubusercontent.com/48724136/222247090-afaf782c-c176-4642-9959-2ba13ea3495a.png)

Local onde arquivo apresenta o menu header.php linha 56 
![image](https://user-images.githubusercontent.com/48724136/222249041-308e8324-a470-4871-a942-6db7f0ba7868.png)

Fico à disposição para qualquer interação CSS necessária

**Comment by wilsonmoura** [comment]
@marcioalvessilva ajustes realizados. Favor validar no ambiente de testes.

**Comment by marcioalvessilva** [comment]
Grato @wilsonmoura 
Validado!
