### ISSUE TITLE
Substituir a palavra Metadados para Metadatos no banner espanhol da instância metadados abertos

### ISSUE THREAD

**Issue by marcoslmori** [bireme/wordpress-themes#166]
https://openmetadata.bvsalud.org/es/

![image](https://user-images.githubusercontent.com/10047460/220907677-4730a90e-8de4-4f12-891e-317a5d1204bb.png)

**Comment by marcoslmori** [comment]
Restabelecimento da instancia de teste: ocomon 
http://suporte.bvs.br//ocomon/geral/ticket_show.php?numero=9047&id=zKBEChguZODVxPR%2B95FoI%2Br7PA4%3D

Atualizar o repositório do wordpress da produção 
http://suporte.bvs.br//ocomon/geral/ticket_show.php?numero=9048&id=JAA1YCVA1hCgr8vpeN%2Bu9%2BX2VBM%3D

**Comment by marcioalvessilva** [comment]
Finalizado
