### ISSUE TITLE
Visualizar data de publicação SOF

### ISSUE THREAD

**Issue by alvesmarilda** [bireme/wordpress-themes#168]
Marcio,

Favor adicionar na visualização a data de publicação da SOF:

https://aps-repo.bvs.br/aps/

Exemplo: 
![image](https://user-images.githubusercontent.com/38661168/234344630-93ec2ebd-8946-4ead-bbb1-cc974045a609.png)

Obrigada!

**Comment by marcioalvessilva** [comment]
Bom dia @alvesmarilda !!!
https://aps-repo.teste.bvs.br/aps/
Por favor validar, antes de enviar para produção

Abraço!

**Comment by alvesmarilda** [comment]
Márcio, Bom Dia!

Teste verificado/validado ok.


Obrigada!

**Comment by marcioalvessilva** [comment]
Chamado aperto no Ocomon Nº 9165
