### ISSUE TITLE
Criar uma solução para um banco de dados de profissionais 

### ISSUE THREAD

**Issue by marcoslmori** [bireme/wordpress-themes#170]
Banco de dados de profissionais 
A partir do bvsalud.org
      Benchamarking 
            Anúncio para a vaga da Luciana
            jobs hunter
                  https://www.jobs-hunter.com/

Analisar plugin:  https://br.wordpress.org/plugins/wp-job-manager/

Desenvolver uma solução WEB
- pode ser um wordpress
- uma página
- ou outra qualquer solução

Objetivos: 
Profissionais que tenha interesse em trabalhar na BIREME se cadastrarem
Auditoria 

Design
- atrativa
- dinâmica
- Visivel
termos de referência 
cadastrar
pessoa física 
pessoa juridica
Funcionalidade
- Usuário final (profissional)
-- formulário de cadastro
-- Banco de dados
- Gestor BIREME
-- ter acesso validado
-- Acessar o banco de dados
-- Pesquisa
-- Edição
-- Delete lógico
-- exportação de dados via csv ou excell

**Comment by marcioalvessilva** [comment]
Issue finalizado, projeto não avançou, caso de retomada abrir novo issue
