### ISSUE TITLE
Ajustes na interface gráfica da BVS Costa Rica

### ISSUE THREAD

**Issue by barrosjo** [bireme/wordpress-themes#173]
https://costarica.teste.bvsalud.org/

- Criar duas imagens de destaque para as páginas: https://www.binasss.sa.cr/dignidad/ e https://www.binasss.sa.cr/economia/ e inserir como carrossel junto com os temas Tabaco e Salud Mental;
- Ajustar container;
- Ajustar responsividade;
- Ajustar acessibilidade

**Comment by barrosjo** [comment]
Criar também uma imagem para LILACS para compor o bloco: 
![image](https://github.com/bireme/wordpress-themes/assets/19578003/075a7499-024c-4adf-8af0-ecff6302bdc3)

Uma imagem para Revistas para compor o bloco:
![image](https://github.com/bireme/wordpress-themes/assets/19578003/84e23e6d-f3ef-4f42-8f6e-7e70fead1c78)

Obs.: O carrossel poderá ocupar todo esse bloco:
![image](https://github.com/bireme/wordpress-themes/assets/19578003/4bd1ad66-97d0-4a01-8c2f-cedb3c2a2eba)

**Comment by marcioalvessilva** [comment]
O site foi refeito, qualquer novo item por favor abrir novo issue
