### ISSUE TITLE
Formulário de Busca MTCI

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/wordpress-themes#174]
Bom dia @wilsonmoura!
Conforme conversado, por favor ajustar os campo de busca para o portal MTCI na teste.

https://mtci.teste.bvsalud.org/
![image](https://github.com/bireme/wordpress-themes/assets/48724136/830a1057-228e-4cae-aa91-b28b9569e26b)

Deve funcionar dentro novo layout assim como funciona na produção atual
https://mtci.bvsalud.org/
![image](https://github.com/bireme/wordpress-themes/assets/48724136/8361a826-03fc-47f3-9356-f4f5da7aafd0)

Muito Obrigado!

**Comment by wilsonmoura** [comment]
Ajustes realizados e validados.
