### ISSUE TITLE
Erros na página https://decs.teste.bvsalud.org/ após clonagem da produção para WordPress 6.3.1

### ISSUE THREAD

**Issue by acecampos** [bireme/wordpress-themes#180]
Oi, @wilsonmoura! Conforme solicitado por e-mail, foram identificados os seguintes erros na página teste.

Pesquisas que não respondem:
- Pesquisa por termo exato
- Pesquisa por ID do descritor
- Pesquisa por código hierárquico
- Pesquisa por qualquer qualificador
- Visualização de registro listado ao clicar na lupa 
Ou seja, **não temos a visualização de nenhuma página que contenha a "ficha do registro".**

Funcionam:
- pesquisa por qualquer descritor com truncador * ou $
- pesquisa por qualquer qualificador com truncador * ou $
- a exibição em lista do resultado
- Explosão da hierarquia com botão +
- Pesquisa no DeCS Finder
- Abas

**Comment by wilsonmoura** [comment]
@acecampos identificamos que o novo servidor de testes precisa de alguns ajustes. Avisaremos assim que os ajustes forem realizados para que possa validar novamente.

**Comment by acecampos** [comment]
Ok. Grata pela atualização.

**Comment by wilsonmoura** [comment]
@acecampos fizemos alguns ajustes. Favor validar novamente.

**Comment by acecampos** [comment]
Wilson, está dizendo que o site está passando por dificuldades técnicas. Não dá nem para abrir.

**Comment by wilsonmoura** [comment]
@acecampos faz alguns minutos que acessei o site e parece que está tudo normal. Por favor, poderia tentar novamente?

**Comment by acecampos** [comment]
@wilsonmoura validado! Foi explicado por você (via _call_) o motivo de não ter o _highlight_ em descritores que constam nas notas de escopo e indexação. Obrigada!
