### ISSUE TITLE
Desenvolver portal da BVS Uruguay Nacional 

### ISSUE THREAD

**Issue by barrosjo** [bireme/wordpress-themes#193]
URL: https://uruguay.teste.bvsalud.org/

Seguir a proposta já aprovada:
![BVS_Uruguay](https://github.com/bireme/wordpress-themes/assets/19578003/fc982e8c-1e66-474c-a9be-034516e7555a)
[Analisis de la BVS Uruguay_Reestructuración_Contenidos_abr2023.pdf](https://github.com/bireme/wordpress-themes/files/13478835/Analisis.de.la.BVS.Uruguay_Reestructuracion_Contenidos_abr2023.pdf)

Essa é a instancia atual do país que deverá ser substituída pela que será desenvolvida: http://www.bvsnacional.uy/wp/

**Comment by marcioalvessilva** [comment]
Issue finalizado, em caso de avanços abrir novo issue com as modificações desejadas
