### ISSUE TITLE
Atualizar arquivo de tradução do portal MTCI

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/wordpress-themes#194]
@wilsonmoura, por favor atualizar arquivo de tradução do portal MTCI

Frase no footer.php ja foi inserida
La responsabilidad de los contenidos de la BVS MTCI es de la Red MTCI Américas

Inglés
The TCIM VHL contents are the responsibility of the TCIM Americas Network.

Portugués
A responsabilidade pelo conteúdo da BVS da MTCI é da Rede MTCI Américas.

![image](https://github.com/bireme/wordpress-themes/assets/48724136/6018eb62-0a78-4b9e-9e3d-ee468e5786c6)

**Comment by wilsonmoura** [comment]
@marcioalvessilva ajustes realizados.
