### ISSUE TITLE
Desenvolver página para a BVS Enfermería dentro da BVS Bolívia

### ISSUE THREAD

**Issue by barrosjo** [bireme/wordpress-themes#195]
Desenvolver uma página dentro da BVS Bolívia https://bolivia.bvsalud.org/ para exibir os conteúdos do país relacionados a área de Enfermagem/BVS Enfermagem. O conteúdo está no documento anexo, enviado por eles. Não incluiremos toda a informação dos programas de pósgraduação, somente nome, universidade e link. 

A ideia é que esse seja uma modelo que possa ser utilizado para as demais BVS temáticas do país. 
[AREA TEMATICA DE EBFERMERUA - BVS BOLIVIA.docx](https://github.com/bireme/wordpress-themes/files/13530882/AREA.TEMATICA.DE.EBFERMERUA.-.BVS.BOLIVIA.docx)

**Comment by barrosjo** [comment]
Bom dia @marcioalvessilva, alguma previsão para a criação dessa página?

**Comment by marcioalvessilva** [comment]
Finalizado, em caso de novidades abrir novo issue
