### ISSUE TITLE
Ajustar redirect no functions do thema MTCI

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/wordpress-themes#196]
Por favor corrigir redirect no portal MTCI

https://mtci.bvsalud.org/multimedia
![image](https://github.com/bireme/wordpress-themes/assets/48724136/541dee09-e3e3-48b1-b1d0-777dffba439b)

Grato!

**Comment by wilsonmoura** [comment]
@marcioalvessilva ajustes realizados. Favor validar.

**Comment by marcioalvessilva** [comment]
Finalizado!
