### ISSUE TITLE
Configurar tamanho caixas seção "Noticias" BVS SMS-SP

### ISSUE THREAD

**Issue by sousajul** [bireme/wordpress-themes#198]
Marcio, configurar um tamanho fixo para as caixas das notícias da seção de notícias da BVS SMS-SP.

Em 11.12 vc fez um css para ajudar, mas vc pediu para abrir um issue assim que passar essa fase eu deixo um valor mínimo de caracteres para essa seção.

![WhatsApp Image 2023-12-11 at 14 32 31](https://github.com/bireme/wordpress-themes/assets/13439949/a4cae97e-beb6-4ad0-8a8f-b231b9edc442)

**Comment by marcioalvessilva** [comment]
Vou fechar este issue. Caso a necessidade persista, por favor, agende um momento para discutirmos a possibilidade de revisitar esta seção e buscar uma solução mais atual, considerando as limitações de configuração que o plugin apresenta para este recurso.
