### ISSUE TITLE
Compatibilizar o desenho do site de comunidade da BVS ECO baseado na própria BVS

### ISSUE THREAD

**Issue by marcoslmori** [bireme/wordpress-themes#200]
https://economia.saude.teste.bvs.br/comunidade/

**Comment by marcoslmori** [comment]
Atualizar o chamado 
http://suporte.bvs.br//ocomon/geral/ticket_show.php?numero=9636&id=dgokMUvGhauLp%2FLzItMMhb4e8%2Bs%3D

**Comment by barrosjo** [comment]
@marcoslmori você abriu o chamado no ocomon para DGI. É o @marcioalvessilva quem deve atualizar?

**Comment by marcioalvessilva** [comment]
Atividade seguiu outro desenvolvimento
