### ISSUE TITLE
Instalação do Plug-in de FAQ na teste do Portal Regional

### ISSUE THREAD

**Issue by pintoros** [bireme/wordpress-themes#201]
Solicito instalação do Plugin https://br.wordpress.org/plugins/ultimate-faqs/ na área de teste do Portal Regional para inclusão de conteúdo na área Como pesquisar. 
Obrigada

**Comment by marcoslmori** [comment]
instalado e documentado em ia
http://suporte.bvs.br//ocomon/geral/ticket_show.php?numero=9652&id=DQKhY1qt81yTw31YIs0f6u9hT6w%3D
