### ISSUE TITLE
[BVS HANSEN] - Comportamento equivocado na caixa de pesquisar quando clica direto no ícone pesquisa  

### ISSUE THREAD

**Issue by marcoslmori** [bireme/wordpress-themes#202]
![image](https://github.com/bireme/wordpress-themes/assets/10047460/512dfe1d-3f2a-4895-961e-4ae848f27a7b)

Ao clicar no ícone pesquisa sem ingressar nenhuma palavra na caixa de pesquisa, será pesquisado a palavra pesquisa no IAhx,

**Comment by marcioalvessilva** [comment]
Finalizado
