### ISSUE TITLE
RefNet - navegação não apresenta totalidade de registros

### ISSUE THREAD

**Issue by pintoros** [bireme/wordpress-themes#205]
Verifiquei hoje que a navegação por páginas no Repositório de estratégias de busca https://bvsalud.org/queries, não apresenta os mais de 1000 registros, somente metade dos mesmos.

Acredito ter a ver com a configuração depois da atualização do qual também está vinculado o chamado #203

**Comment by pintoros** [comment]
Em testes realizados em https://teste2023.bvsalud.org/queries/ utilizando o plugin Relevanssi, a busca funciona, mas não a navegação e também não apresenta os ultimos posts quando clicamos em "veja mais". Ao desabilitar o Relevanssi, o conteúdo mais recente e a navegação passa a apresentar os 991 posts na navegação.

@ramosluc sugeriu testar o plugin https://wordpress.org/plugins/swiftype-search/

A expectativa é que funcione tanto a busca por campos específicos, como a navegação pelos mais de 900 posts, assim como o carregamento dos posts mais recentes (2024).

Exemplos de parâmetros de pesquisa de acordo com os campos recuperáveis:

Responsável: 
LMIC Country Filters
OPAS-OMS

Assuntos principais
vert4t54353we3qr3q4e
Saude Universal

Descrição
systematic reviews
Politicas de Saúde

* observar que esses termos podem ser comuns nos campos de títulos, assunto etc. O que permitirá uma recuperação mais precisa é a inclusão de aspas. Ex.: "OPAS-OMS" . Isso era aplicável na versão anterior desse sistema. 
* Outra forma de garantir isso é habilitar um menu de campos associado a caixa de busca.
* Hoje a recuperação só é feita por palavras do título (campo título dos posts)

**Comment by ramosluc** [comment]
Pessoal, analisando de forma mais profunda essa questão dos posts não aparecerem no widget, percebi que há a necessidade de realizar a instalação de alguns elementos conforme a mensagem.

Ultimate Posts Widget: This plugin provides a classic widget type, and needs the [Classic Widgets](https://wordpress.org/plugins/classic-widgets/) plugin to function properly on this WordPress version.

O Widget Ultimate posts realiza a coleta e mostra as postagens após clicar em veja mais na página inicial. Por isso essa instalação provavelmente pode auxiliar na configuração de mostragem de posts.

A conta de usuário que foi criada para administração do site não apresenta o painel de instalação de plugins, por gentileza instalar o classic widgets.

**Comment by marcoslmori** [comment]
classic widgets instalado na instância de teste e em rede teste2023.bvsalud.org

**Comment by ramosluc** [comment]
Pessoal, o bug de paginação foi corrigido, foram realizadas as alterações e as entradas estão aparecendo conforme o solicitado no link 

https://teste2023.bvsalud.org/queries/?l=pt_BR

Acessando o link em "Veja mais" será possivel visualizar todos os posts colocados totalizando 98 páginas até o momento, totalizando 970 entradas.

Para encontrar o problema, foi necessário realizar uma análise e modificação no código do tema e dos plugins Relevanssi e WP_pagenavi.  

O filtro relevanssi_throttle_limit no Relevanssi é usado para limitar o número de posts retornados nos resultados de busca, evitando sobrecarregar o servidor. Por padrão, isso pode estar definido para 500 posts. Foi adicionando um filtro no arquivo functions.php para aumentar o limite para 1000.

Para aumentar o limite de throttling, use:

php
add_filter('relevanssi_throttle_limit', function($limit) {
    return 1000; // Ajuste o limite conforme necessário
});
Para desativar o limite de throttling, use:

php
add_filter('relevanssi_throttle_limit', '__return_false');
Esses ajustes devem permitir que você exiba todos os posts nos resultados da busca.

Essa configuração pode ser realizada também por meio do link:

https://teste2023.bvsalud.org/wp-admin/network/site-settings.php?id=4 

Não havendo assim a necessidade de entrar no arquivo de código para aumentar a carga de posts.

No plugin do WP_pagenavi foi necessário dimensionar a quantidade de posts por página e também ajustar os multiplos para visualizar corretamente todas as entradas.

E por fim foi realizado um troubleshooting no tema, analisando o issue https://github.com/bireme/wordpress-themes/issues/197 que foi feita a codificação do "veja mais" na home.

Fico a disposição para mais esclarecimentos caso necessário.

Atenciosamente.

**Comment by marcoslmori** [comment]
OXI!!!  legal, bem legal!!! 
> Para encontrar o problema, foi necessário realizar uma análise e modificação no código do tema e dos plugins Relevanssi e WP_pagenavi. 
Foi só para encontrar o problema ou vai ter que fazer commit na produção também do tema?

@pintoros Por favor, validar!!!!

**Comment by ramosluc** [comment]
Não será necessário commit na produção, já foi alterado diretamente na instancia. para realizar o aumento de carga é só entrar no link atualmente está em 1000.

https://teste2023.bvsalud.org/wp-admin/network/site-settings.php?id=4

Em Sites > All sites > Editar ([teste2023.bvsalud.org/queries] > Configurações > 

![throttle](https://github.com/user-attachments/assets/b243a432-188a-4aee-aa86-6d7d5dafe94d)


na parte conforme o print em anexo.

**Comment by marcoslmori** [comment]
Ok. vamos esperar a validação da Rose e depois vc ajusta a produção

**Comment by ramosluc** [comment]
Pessoal, foram realizadas as alterações no ambiente de produção, por gentileza @pintoros @marcoslmori validar.

https://bvsalud.org/queries/

Atenciosamente.

**Comment by pintoros** [comment]
@ramosluc e @marcoslmori, notei na produção que a pesquisa não alcança resultado no post mais recente - Febre Oropouche. Os demais estão OK!
Quanto aos campos pesquisáveis, parece que estão de acordo.

**Comment by marcioalvessilva** [comment]
Finalizado!
