### ISSUE TITLE
No e-blueinfo criar o país Honduras

### ISSUE THREAD

**Issue by anakatiacamilo** [bireme/wordpress-themes#209]
@Lizbiruel, por favor, passar o texto sobre a informação nos três idiomas (pt-br, es e en) para o @marcioalvessilva pode criar a página https://e-blueinfo.bvsalud.org/informacoes-dos-paises/

**Comment by anakatiacamilo** [comment]
@marcioalvessilva 
                 "pt" => $_site . '/dados-de-honduras/',
                 "es" => $_site . '/es/datos-de-honduras/',
                 "en" => $_site . '/en/data-from-honduras/'

**Comment by marcoslmori** [comment]
@Lizbiruel E as imagens das coleções e comunidades para @marcioalvessilva . Thanks

**Comment by anakatiacamilo** [comment]
@marcioalvessilva, por favor, incluir Honduras na página inicial do e-bluinfo nos três idiomas. Grata

![image](https://github.com/bireme/wordpress-themes/assets/19270675/a60aadca-2e50-4240-89a2-99575eb769c5)

**Comment by marcioalvessilva** [comment]
@anakatiacamilo - páginas Honduras criadas e home-age atualizada, por favor validar.

**Comment by anakatiacamilo** [comment]
Perfeito @marcioalvessilva Obrigada.
