### ISSUE TITLE
Rodapé do Diretório da Rede BVS com letras em branco

### ISSUE THREAD

**Issue by suelisuga** [bireme/wordpress-themes#211]
Solicito correção da cor das fontes apresentadas no rodapé do Diretório da Rede BVS que estão em branco e dificultam a leitura do conteúdo. https://bvsalud.org/centros/

Imagem:

![image](https://github.com/user-attachments/assets/75688a2e-dd3b-4861-859d-6a809aaf0d2d)

Muito obrigada!

**Comment by marcioalvessilva** [comment]
Foi aplicado ajuste na versão de teste (https://teste2023.bvsalud.org/centros) e aberto um chamado para atualizar na produção 9736.
Continuo à disposição.

**Comment by marcioalvessilva** [comment]
Finalizado!
