### ISSUE TITLE
Categorias da FAQ LILACS precisam ser linkáveis

### ISSUE THREAD

**Issue by suelisuga** [bireme/wordpress-themes#212]
Preciso linkar a FAQ do processo de seleção de periódicos LILACS Brasil na plataforma de avaliação de periodicos da LILACS. Para isso, solicito que as categorías tenham link para que possamos redireconar o usuário ao ponto exato da FAQ.

<img width="713" alt="image" src="https://github.com/user-attachments/assets/07a23b04-d57c-402a-bf46-f5ee99b227e6">

Daqui: https://avaliacao.lilacs.bvsalud.org/public/faq

Para cá:
<img width="779" alt="image" src="https://github.com/user-attachments/assets/6faa32ca-1931-4a79-b652-5943e35e68cc">

Muito obrigada!

**Comment by marcioalvessilva** [comment]
Issue fechado porque assunto esta sendo tratado no https://github.com/bireme/wordpress-themes/issues/223
