### ISSUE TITLE
Incluir metadados no código fonte do portal LILACS

### ISSUE THREAD

**Issue by suelisuga** [bireme/wordpress-themes#213]
Solicito inclusão da descrição do portal LILACS no código fonte:
diagnostico do Page Speech Insights:
![image](https://github.com/user-attachments/assets/319fb2d6-9951-4894-90d8-44ed2d62338a)

Atualmente temos somente:
![image](https://github.com/user-attachments/assets/e471e835-7af9-4f14-a567-f2d033a0a958)

E a informação incluida no WP não aparece corretamente no código da página:
![image](https://github.com/user-attachments/assets/c1f815d1-446f-4731-b7f9-4df977ca142e)

E verifiquei que é possível incluir em múltiplos idiomas:
![image](https://github.com/user-attachments/assets/a020179a-ca0b-49e5-86b3-dffd258ee64f)

**Então solicito:**

Incluir no meta name =
Author:
- "author" lang="pt" content="LILACS - BIREME/OPAS/OMS"
- "author" lang="es" content="LILACS - BIREME/OPS/OMS"
- "author" lang="en" content="LILACS - BIREME/PAHO/WHO"

Title:
- "title" lang="pt" content="LILACS - Literatura Latino-Americana e do Caribe em Ciências da Saúde  - Informação e evidência científica e técnica em saúde da América Latina e Caribe - BIREME/OPAS/OMS"
- "title" lang="es" content="LILACS - Información y evidencia científica y técnica en salud de América Latina y el Caribe  - BIREME/OPS/OMS"
- "title" lang="es" content="LILACS - Scientífic and technic information and evidence of Latin-american and Caribbean Countries  - BIREME/PAHO/WHO"

Description:
- "description" lang="pt" content="Explore a LILACS, a base de dados mais completa em saúde na América Latina e Caribe, com artigos científicos, livros e teses. Acesse gratuitamente milhares de textos completos e recursos acadêmicos."
- "description" lang="es" content="Explore LILACS, la principal base de datos de salud en América Latina y el Caribe, con artículos científicos, libros y tesis. Acceda gratuitamente a miles de textos completos y recursos académicos."
- "description" lang="en" content="Explore LILACS, the leading health database in Latin America and the Caribbean, featuring scientific articles, books, and theses. Access thousands of full-text resources for free."

Keywords:
- "keywords" lang="pt" content="LILACS, base de dados de saúde, artigos científicos, saúde América Latina, pesquisa em saúde, publicações médicas, literatura científica, ciências da saúde, BVS, Biblioteca Virtual em Saúde, BIREME, evidência científica em saúde, ensaios clínicos, revisões sistemáticas, avaliação de tecnologias sanitárias, guias de prática clínica, DeCS, Metodologia LILACS, Rede LILACS, boas práticas editoriais em saúde, avaliação de periódicos em saúde"
- "keywords" lang="es" content="LILACS, base de datos de salud, artículos científicos, salud América Latina, investigación en salud, publicaciones médicas, literatura científica, ciencias de la salud, BVS, Biblioteca Virtual en Salud, BIREME, evidencia científica en salud, ensayos clínicos, revisiones sistemáticas, evaluación de tecnologías sanitarias, guías de práctica clínica, DeCS, metodología LILACS, Red LILACS, buenas prácticas editoriales en salud, evaluación de revistas en salud"
- "keywords" lang="en" content="keywords" content="LILACS, health database, scientific articles, Latin America health, health research, medical publications, scientific literature, health sciences, VHL, Virtual Health Library, BIREME, scientific evidence in health, clinical trials, systematic reviews, Biomedical Technology Assessment, Biomedical, Practice Guidelines, technical reports, DeCS, LILACS Methodology, LILACS Network,, good editorial practices in health, journal evaluation in health"

Por fim, não sei estimar a importância dessa tag, mas foi recomendado incluir 
![image](https://github.com/user-attachments/assets/a281c28f-c175-44f5-82cf-72b540aeba49)

Muito obrigada!

**Comment by marcioalvessilva** [comment]
Fiz uma analise sobre sua solicitação e apresento considerações antes de avançar
1 - Keywords e uma meta obsoleta nos dias atuais 
2* - Description e uma meta importante, porém cada páginas e post deve ter a sua description, não uma global para o site, pois é uma descrição do conteudo da página não do site
3 - A meta robots é para indexar nos buscadores, por padrão hoje em dia ja entende que devem ser indexadas, não adiciona valor com a configuração index, follow

Sobre o idem 2, existem plugins para melhorar o SEO de cada página exemplo Yoast SEO (Não sei se esta homologado nos plugins usados pela BIREME) para fazer isso manual acredito que precise fazer uma programação usando o plugin ACF e cadastrar o conteudo em cada post ou pagina. 

Aguardo orientações

**Comment by marcioalvessilva** [comment]
Em caso de continuidade dessa necessidade por favor reabrir issue ou criar novo.

**Comment by suelisuga** [comment]
solicito instalar a ferramenta ou instruir onde devemos incluir os metadados necessários.
