### ISSUE TITLE
Atualizar instituições - Controle de Cancer

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/wordpress-themes#215]
@ramosluc por favor atualizar conteúdo da primeira coluna (Instituições).
Para atualizar essa área você precisa inserir as imagem e links dentro da coluna 1 (Menu Apareceria -> Widgets).
O conteúdo será enviado pela Andrea no seu email

https://controlecancer.bvs.br/
![image](https://github.com/user-attachments/assets/af64bad4-e3d6-416c-8737-a23d55576691)

**Comment by ramosluc** [comment]
@marcioalvessilva segue atualizado.

[BVS Prevenção e Controle de Câncer](https://controlecancer.bvs.br/)

Segue em anexo tutorial ilustrado conforme solicitado pelo email da Andrea.

Atenciosamente.

[edicao_portais_relacionados_controle_cancer.pdf](https://github.com/user-attachments/files/16756678/edicao_portais_relacionados_controle_cancer.pdf)

**Comment by marcioalvessilva** [comment]
Grato @ramosluc
