### ISSUE TITLE
Ajustar página LILACS Plus para ser parte da página Coleção (em português) e criar as versões em espanhol e inglês

### ISSUE THREAD

**Issue by suelisuga** [bireme/wordpress-themes#219]
Solicito alteração do formato da página LILACS Plus de modo a torná-la um dos itens da página Coleção. https://bvsalud.org/colecao/ e incluir item LILACS Plus no menu.
Entendo que novo link será: https://bvsalud.org/colecao/#lilacs-plus

Também solicito criar as páginas em espanhol e inglês.

Da forma como criei para atender ao lançamento técnico, o conteúdo português ficou publicado em: https://bvsalud.org/lilacs-plus/

Todos os textos para Portal Regional da BVS e interface de pesquisa - conteúdo com imagens em: https://paho.sharepoint.com/:w:/r/sites/BIR/TC/TC/Processos/LILACS/LILACS-Plus/Colecao-LILACS-Plus.docx?d=wa95be37049eb4ae6a157773e03f186d1&csf=1&web=1&e=94GzGO

Página em português: 

**O que é LILACS Plus** 

É uma coleção de publicações e outros documentos científicos e técnicos em saúde da América Latina e Caribe. 

É uma estratégia para reunir a literatura que está fragmentada e dispersa em diversas bases de dados e repositórios institucionais. É uma resposta para separar e destacar na BVS a produção da Região. 

**Como é formada a coleção LILACS Plus** 

LILACS Plus é a base de dados LILACS somada às bases de dados da América Latina e Caribe disponíveis na BVS, o repositório IRIS da OPAS e a coleta de dados documentos da AL&C de MEDLINE e outras bases de dados internacionais. 

**Critérios de inclusão** 

São aplicados os critérios para seleção na coleção da BVS: 

- País de publicação na AL&C;  
- País de afiliação institucional da AL&C;  
- País de AL&C como tema, independente do país de  publicação.  

**Filtros para seleção da documentação** 

As bases de dados que têm como critério de seleção o registro exclusivo de documentos da AL&C foram incluídas na íntegra na LILACS Plus. 

No caso de bases de dados que incluem documentos de outros países, como MEDLINE, BDENF, MOSAICO e outras, foram aplicados filtros de busca com os critérios referidos no tópico anterior para selecionar apenas documentos da AL&C. 

Acesse os filtros aplicados nessas bases de dados no Repositório de Estratégias de Busca da BVS. 

**Periodicidade de atualização** 

A cada dois dias o processamento e publicação de dados é finalizado. 

**Comentários** 

Se você tiver alguma dúvida ou comentário sobre a LILACS Plus, entre em contato conosco usando o título "LILACS Plus" em sua mensagem. 

 

------------------------------------------------------------------ 
Página em espanhol: 

**Que es LILACS Plus** 

Es una colección de publicaciones y otros documentos científicos y técnicos en Salud de América y el Caribe. 

Es una estrategia para reunir la literatura que está fragmentada y dispersa en diversas bases de datos y repositorios institucionales. Es una respuesta para separar y destacar en la BVS la producción de la Región.   

**Como es conformada la colección de LILACS Plus** 

LILACS Plus es la base de datos LILACS sumada de las bases de datos de América Latina y Caribe disponibles en la BVS, el repositorio IRIS de la OPS y la cosecha de datos de los documentos de AL&C de MEDLINE y otras bases de datos internacionales. 

**Criterios de inclusión** 

Se aplica los criterios para selección en la colección de la BVS: 

- País de publicación en ALyC; 
- País de afiliación institucional de ALyC; 
- País de ALyC como tema, independiente del país de la publicación. 
 
**Filtros para recolección/cosecha de datos** 

Las bases de datos que tienen como criterio de selección registrar exclusivamente documentos de AL&C fueron incluidas en su totalidad en LILACS Plus. 

En los casos de las bases de datos que incluyen documentos de otros países, como MEDLINE, BDENF, MOSAICO y otras, se aplicaron filtros de búsqueda con los criterios referidos en el tópico anterior para seleccionar solamente documentos de AL&C. 

Acceda a los filtros aplicados en estas bases de datos en el [Repositorio de Estrategias de Búsqueda de la BVS](https://bvsalud.org/queries/search_strategy/filtro-lilacs-plus/?l=es_ES). 

**Periodicidad de la actualización** 

A cada dos dias es realizado el procesamiento y publicación de datos. 

**Comentarios** 

Si tienes alguna duda o comentario sobre LILACS Plus, por favor [contáctanos](https://bvsalud.org/es/pregunte-al-bibliotecologo/) usando el título "LILACS Plus" en su mensaje. 

 

------------------------------------- 
Página em inglês: 
 

**What is LILACS Plus**  

It is a collection of scientific and technical publications in Health from Latin America and the Caribbean (LAC). 

It is a strategy to gather literature that is fragmented and dispersed across various databases and institutional repositories. It is a response to separate and highlight the region's production in the Virtual Health Library (VHL). 

**How is the LILACS Plus collection composed?** 

LILACS Plus consists of the LILACS database combined with the Latin American and Caribbean databases available in the VHL, the IRIS repository of the Pan American Health Organization (PAHO), and the harvesting of data from Latin America and the Caribbean documents from MEDLINE and other international databases.  

**Inclusion criteria**  

The criteria for selection in the VHL collection are applied:  

- Country of publication in LAC 
- Institutional affiliation in LAC 
- LAC country as a subject, regardless of the country of publication 

**Data collection and harvesting filters** 

Databases that exclusively register documents from LAC, according to their selection criteria, have been fully included in LILACS Plus. 

For databases that include documents from other countries, such as MEDLINE, BDENF, MOSAICO, and others, search filters were applied based on the criteria mentioned in the previous section to select only LAC documents. 

Access the filters applied to these databases in the [VHL Search Strategies Repository](https://bvsalud.org/queries/search_strategy/filtro-lilacs-plus/?l=en_US).  

**Update frequency** 

Data processing and publication are carried out every two days.  

**Comments**  

If you have any questions or comments about LILACS Plus, please [contact us](https://bvsalud.org/en/ask-a-librarian/) using the subject "LILACS Plus" in your message.  

 

Muito obrigada!

**Comment by marcioalvessilva** [comment]
@suelisuga por favor validar conteúdo e me avisar para eu excluir página atual.
https://bvsalud.org/es/coleccion/#menu-lilacsplus

@viniciusandrade  por favor atualizar endereço do icone (i) dentro do IAHx na aba LILACS plus
pt - https://bvsalud.org/colecao/#menu-lilacsplus
en - https://bvsalud.org/en/collection/#menu-lilacsplus
es - https://bvsalud.org/es/coleccion/#menu-lilacsplus
![image](https://github.com/user-attachments/assets/87b2b5ca-2201-4358-b254-1ce8d75793bd)



Obrigado!!!

**Comment by viniciusandrade** [comment]
@marcioalvessilva links atualizados do icone de informação. Abraços.

**Comment by marcioalvessilva** [comment]
Grato @viniciusandrade, fiz o teste e esta tudo ok!
