### ISSUE TITLE
Incluir link do LILACS Support Center no menu Contato

### ISSUE THREAD

**Issue by suelisuga** [bireme/wordpress-themes#220]
Solicito substituição do link do menu Contato do portal da LILACS para a página de FAQ, renomeada de LILACS support center

DE: https://lilacs.bvsalud.org/contato-livezilla/
POR: https://lilacs.bvsalud.org/faq-pt/

DE: https://lilacs.bvsalud.org/es/contacto-livezilla/
PARA: https://lilacs.bvsalud.org/es/faq-es/

DE: https://lilacs.bvsalud.org/en/livezilla-contact/
PARA: https://lilacs.bvsalud.org/en/faq/

Muito obrigada!

**Comment by marcioalvessilva** [comment]
Atualizado, por favor validar e fechar o issue

**Comment by suelisuga** [comment]
Validado. Obrigada!
