### ISSUE TITLE
Revisar estilo da página de FAQ

### ISSUE THREAD

**Issue by suelisuga** [bireme/wordpress-themes#221]
Solicito harmonizar o estilo da página.

A estrutura de cada página apresenta:

- Categoria
--Pergunta
--- Resposta

Atualmente Categoria e Pergunta estão com o mesmo estilo, o que gera um visual pesado, pois as perguntas estão em negrito:
<img width="895" alt="image" src="https://github.com/user-attachments/assets/b4a164c0-b21c-4909-b55b-2170fc887755">

Muito obrigada!

**Comment by marcioalvessilva** [comment]
Segue print de ajuste CSS
Categoria (ficou com tamanho padrão h3 )
- Pergunta  ( h4 tamanho 16px margem esquerda 20px, icone menor)
-- Resposta (p tamanho padrão e margem esquerda 40px)

Qualquer novo ajuste fico à disposição
![image](https://github.com/user-attachments/assets/8257b571-89d0-40b4-90fc-e62dee8286a7)
