### ISSUE TITLE
Solicito excluir nome do criador da FAQ

### ISSUE THREAD

**Issue by suelisuga** [bireme/wordpress-themes#222]
Atualmente as respostas de cada pergunta da FAQ está sendo apresentada. Solicito excluir.

<img width="895" alt="image" src="https://github.com/user-attachments/assets/13d840d9-c908-4575-9e81-f667c89ce28c">

Muito obrigada!

**Comment by marcioalvessilva** [comment]
Por favor validar

**Comment by suelisuga** [comment]
validado. obrigada
