### ISSUE TITLE
Link da categoria envia para todo o conteúdo da FAQ

### ISSUE THREAD

**Issue by suelisuga** [bireme/wordpress-themes#223]
Solicito corrigir o link gerado pelas categorias. Ao invés do link enviar para as perguntas dessa categoria, ele envia para a FAQ completa:

<img width="895" alt="image" src="https://github.com/user-attachments/assets/65604612-1bb7-446c-93bb-1cb2e7cf073d">

Resultado ao clicar no link da categoria Base de dados LILACS
<img width="902" alt="image" src="https://github.com/user-attachments/assets/17442897-49e4-459e-9ddc-9937a39187f6">

Muito obrigada!

**Comment by marcioalvessilva** [comment]
Os issue abaixo estão conectados, a solução seria criar paginas para categorias e inserir link para essa página
https://github.com/bireme/wordpress-themes/issues/226, https://github.com/bireme/wordpress-themes/issues/225, https://github.com/bireme/wordpress-themes/issues/223

**Comment by marcioalvessilva** [comment]
Finalizado!
