### ISSUE TITLE
Ao clicar no Permalink, o link apresentado na URL é um número. Seria possível trocar o número pela pergunta por extenso?

### ISSUE THREAD

**Issue by suelisuga** [bireme/wordpress-themes#224]
Qdo clicamos no Permalink, o link apresentado na URL é um número. Seria possível trocar o número pela pergunta por extenso? No exemplo: FAQ 20490 (ou algo assim)

<img width="919" alt="image" src="https://github.com/user-attachments/assets/2ead07e1-799c-4b57-b42a-bdc96c3cf072">

Muito obrigada!

**Comment by marcioalvessilva** [comment]
Acredito que não é possivel, pois o plugin ja tem um post separado com a url, veja abaixo os dois exemplos

Dentro das faqs
https://lilacs.bvsalud.org/faq-pt/?Display_FAQ=20490

Post separado
https://lilacs.bvsalud.org/ufaqs/quem-envia-os-dados-das-revistas-para-a-lilacs-express/

**Comment by suelisuga** [comment]
ok
