### ISSUE TITLE
Alterar posição das caixas de Lista de Dispositivos e Lista de Países

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/wordpress-themes#26]
Lista de dispositivos deve ser alterado para posição mais a direita.

**Comment by marcioalvessilva** [comment]
Alterado
https://github.com/bireme/wordpress-themes/search?q=26355273839721a7960fc4c9e2275d21b8c47a9b&type=Commits

**Comment by marcioalvessilva** [comment]
Finalizado
