### ISSUE TITLE
Refnet - Description of the search 

### ISSUE THREAD

**Issue by pintoros** [bireme/wordpress-themes#30]
Description of the search -  Solicito reverter esse campo para editor de texto com a possibilidade de incluir link. Informo que este campo é obrigatório no preenchimento. 
https://bvsalud.org/queries/wp-admin

**Comment by wilsonmoura** [comment]
Campo ajustado no ambiente de produção. Vale reforçar que os botões para adicionar as tags de idiomas só são exibidos em campos de área de texto.
