### ISSUE TITLE
Refnet - URL to Search Result 

### ISSUE THREAD

**Issue by pintoros** [bireme/wordpress-themes#31]
Campo URL to Search Result * incluir tags de idioma. 
Diminuir a área do campo, no máximo serão reportadas 3 linhas, 
https://bvsalud.org/queries/wp-admin

**Comment by wilsonmoura** [comment]
@pintoros Esse campo é do tipo **editor de texto**. Os botões para adicionar as tags de idiomas só são exibidos em campos do tipo **área de texto**. Favor confirmar se mantemos o campo como está ou se realizamos esse ajuste.
