### ISSUE TITLE
RefNet - Search Details 

### ISSUE THREAD

**Issue by pintoros** [bireme/wordpress-themes#32]
Campo Search Details  sumiram as tags de idioma - Incluir explicação :
_Use for any type of information about the search. Field not available on the public interface._

https://bvsalud.org/queries/wp-admin

**Comment by wilsonmoura** [comment]
Botão de para inserir tags de idiomas - resolvido em #37 
Explicação incluída no campo conforme solicirado.

**Comment by pintoros** [comment]
Acabei de acessar e as tags sumiram de novo. Todos os campos de texto da área About the search precisam de tags de idioma.
Em nenhum campo de Search strategy deve constar a tag de idiomas.

![Search strategy - Copia](https://user-images.githubusercontent.com/29313904/89955649-e26f9000-dc09-11ea-92a7-79ea5a4c65e9.PNG)
![About the search - Copia](https://user-images.githubusercontent.com/29313904/89955650-e3a0bd00-dc09-11ea-8225-e0e24e1dcf12.PNG)

**Comment by wilsonmoura** [comment]
@pintoros Pelo o que entendi, tinham sumido os botões para inserir as tags de idiomas. E isso realmente ocorreu e foi resolvido na issue #37. Agora, se você estiver falando que sumiram as tags dentro dos conteúdos, pode ter sido decorrente da otimização da base de dados que foi feita para atualizar todo o ambiente. Nesse caso, vai ter que inserir novamente as tags nos conteúdos. Se for o caso, poderia dar mais detalhes sobre isso?

**Comment by wilsonmoura** [comment]
@pintoros Esse campo é do tipo **editor de texto**. Os botões para adicionar as tags de idiomas só são exibidos em campos do tipo **área de texto**. Favor confirmar se mantemos o campo como está ou se realizamos esse ajuste.
