### ISSUE TITLE
Refnet - VHL Instance

### ISSUE THREAD

**Issue by pintoros** [bireme/wordpress-themes#35]
Esse campo foi desabilitado, porém ainda aparece na interface e na área de administração do perfil Administrador e não permite apagar os dados que já existem e estão desatualizados

VHL Instance in Portuguese 
VHL Instance in Spanish
VHL Instance in English

![Campos obsoletos_administrador](https://user-images.githubusercontent.com/29313904/89461977-1e56b100-d743-11ea-9efa-8c606e94d324.PNG)

**Comment by wilsonmoura** [comment]
@pintoros olhei nas configurações desse campo e ele não estava desativado. Realizei ajustes e agora sim está desativado. Favor verificar no ambiente de produção.

**Comment by wilsonmoura** [comment]
@pintoros conforme conversamos, removemos os campos VHL Instance e Search Details da interface pública.
