### ISSUE TITLE
Incluir links para redes sociais nas páginas do portal GIM (WordPress)

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/wordpress-themes#41]

**Comment by renatomurasaki** [comment]
@marcoslmori e @marcioalvessilva por favor, ativem no WordPress do GIM algum plug-in homologado de redes sociais para que fique disponível em todas as páginas e posts, inclusive na homepage, por favor. Foi observado isso durante a reunião de hoje do Global Library Group, quando demonstrei que os acessos ao portal diminuiram e que precisamos ampliar as ações de divulgação.

**Comment by marcoslmori** [comment]
sendo testado o plugin https://es.wordpress.org/plugins/ultimate-social-media-icons/ que já tínhamos instalado em mtci.bvsalud.org.  Os outros dois plugins homologados já estão sem atualizações a mais de um ano e não foi testado com as ultimas versões de wordpress

**Comment by marcioalvessilva** [comment]
Redes Sociais Inseridas
https://www.globalindexmedicus.net/
