### ISSUE TITLE
Atualizar rodapé do GIM

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/wordpress-themes#43]
Substituir o texto:

```
Library and Information Networks for Knowledge Unit
(LNK/WHO)

```
Por:

`WHO Library and Digital Information Networks`

**Comment by renatomurasaki** [comment]
As traduções correspondentes estão na própria página da OMS. Siga o link que está no rodapé do GIM. Somente português não tem disponível.

Do inglês - WHO Library and Digital Information Networks as traduções são

fr - https://www.who.int/library/fr/
Bibliothèque et réseaux d'information numérique de l'OMS

es - https://www.who.int/library/es/
Biblioteca y Redes de Información Digital de la OMS

ar - https://www.who.int/library/ar/
مكتبة منظمة الصحة العالمية وشبكات المعلومات الرقمية

ru - https://www.who.int/library/ru/
Библиотека и цифровые информационные сети ВОЗ

zh - https://www.who.int/library/zh/
世卫组织图书馆和数字信息网络

pt - Biblioteca e Redes de Informação Digital da OMS

Deve remover a sigla LNK/WHO

**Comment by marcioalvessilva** [comment]
Textos atualizados, por favor validar!
Obs: em pt foi mantido o link para página em inglês

**Comment by renatomurasaki** [comment]
Perfeito. Obrigado
