### ISSUE TITLE
Incluir as opções de formatação de texto que existe no campo de descrição para o campo de resumo

### ISSUE THREAD

**Issue by marcoslmori** [bireme/wordpress-themes#6]
![image](https://cloud.githubusercontent.com/assets/10047460/21266820/d68ba3ec-c38e-11e6-9043-979fab866623.png)

tema do boletin
https://github.com/bireme/wordpress-themes/tree/master/boletim-bireme

**Comment by wilsonmoura** [comment]
Resolvido com o plugin [Rich Text Excerpts](https://br.wordpress.org/plugins/rich-text-excerpts/).
