### ISSUE TITLE
Testar e Ajustar funcionamento do tema - Open Metadata

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/wordpress-themes#61]
Relacionado ao #49

**Comment by renatomurasaki** [comment]
@marcioalvessilva entendo que está ok. Se tivermos problemas ou necessidade de ajustes, criaremos novo issue.

**Comment by renatomurasaki** [comment]
https://github.com/bireme/wordpress-themes/tree/master/openmetadata
