### ISSUE TITLE
Atualizar conteúdo do carrossel GIM

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/wordpress-themes#69]
@marcioalvessilva favor manter somente no carrossel os destaques relacionados a "More than 2 million of bibliographic records on health sciences" e "COVID-19 - Technical and scientific information resources" e os demais desativar para dar lugar a um novo destaque, como segue:

EN - "Primary health care around the world: delivering health services to people where they need it"
PT - "Atenção primária à saúde no mundo: prestando serviços de saúde às pessoas onde elas precisam"
ES - "Atención primaria de salud no mundo: prestación de servicios de salud a las personas donde los necesitan"

Favor utilizar Google Translator para os demais idiomas.

Utilizar a imagem da página 11 do documento https://docs.google.com/viewerng/viewer?url=https://www.uhcpartnership.net/wp-content/uploads/2021/07/Magazine_Stories-from-the-field_issue-6_WEB_single_July-2021.pdf

![image](https://user-images.githubusercontent.com/1226218/126657897-a8c01f4b-cb7e-4716-993a-c8cfe8c4d91b.png)

**Comment by marcioalvessilva** [comment]
@renatomurasaki pode me confirmar o link do novo banner?
Acredito que seja pra o próprio pdf, caso seja, minha pergunta é se existe o pdf em outros idiomas?
Aguardo para finalizar. grato!

**Comment by renatomurasaki** [comment]
@marcioalvessilva o link é https://www.uhcpartnership.net/stories-from-the-field-issue6-2021/

Usar este link em todos os idiomas, por favor.

**Comment by marcioalvessilva** [comment]
Banners publicados, por favor validar!

**Comment by renatomurasaki** [comment]
@marcioalvessilva o novo destaque está ok, entretanto saiu um destaque que deveria continuar:  "COVID-19 - Technical and scientific information resources"

**Comment by marcioalvessilva** [comment]
@renatomurasaki, os banners  COVID-19 - Scientific and technical information in the Virtual Health Library - BIREME/PAHO estão online novamente!

**Comment by renatomurasaki** [comment]
@marcioalvessilva não é esse... é o que tem o título "echnical and scientific information resources" e a palavra COVID-19 na imagem do banner. O link dele é uma âncora para a seção na homepage com destaques para todos os recursos sobre COVID-19.

**Comment by marcioalvessilva** [comment]
@renatomurasaki, banners alterado!

**Comment by renatomurasaki** [comment]
@marcioalvessilva agora sim! Obrigado!
