### ISSUE TITLE
Inclusão de novos campos

### ISSUE THREAD

**Issue by pintoros** [bireme/wordpress-themes#7]
Solicito incluir mais 3 campos para estratégias de busca (colapsados por default), com os seguintes titulos e elementos:

Label para cada um dos 3 campos:
1o) Pubmed search strategy
2o) Cochrane search strategy
3o) Other databases search strategy (Embase, Web of Science, etc.)

Elementos de cada campo
1o) Search Strategy information - este será um campo livre
2o) Search Strategy expression - também livre (precisa permitir muitos caracteres)

**Comment by wilsonmoura** [comment]
@pintoros Os novos campos foram adicionados conforme solicitação.
