### ISSUE TITLE
Alterar ordem dos destaques da seção COVID-19 na home do GIM

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/wordpress-themes#70]
Colocar o destaque "Global research on coronavirus disease (COVID-19)" na segunda posição (depois do "See information on COVID-19 published in the Regional Indexes Medici")

**Comment by marcioalvessilva** [comment]
@renatomurasaki , ordem dos banners alterada!

**Comment by renatomurasaki** [comment]
@marcioalvessilva obrigado!
