### ISSUE TITLE
Revisar favicon dos sites hospedados na BIREME que foram recentemente atualizados ou instalados

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/wordpress-themes#71]
@marcoslmori este tema é recorrente e anteriormente identificado. Por favor, revisar o processo de atualização ou instalação dos sites para que o favicon seja incluído no processo.

Alguns exemplos que estão utilizando o favicon padrão do WordPress

https://boletin.bireme.org/
https://brasil.bvs.br/
https://mtci.bvsalud.org/

**Comment by marcoslmori** [comment]
Ajustado nos exemplos, farei uma revisão nos que já estão publicados e já está definido nos processos de atualização do WP

Revisão chamado 8119 do ocomon:  http://suporte.bvs.br//ocomon/geral/ticket_show.php?numero=8119&id=211YlVjnoR+zz+ukB9ObReFdb5s=
