### ISSUE TITLE
BVS MS - IAHx - Ajustar a paleta de cores da instancia do IAHx + barra institucional

### ISSUE THREAD

**Issue by marcoslmori** [bireme/wordpress-themes#72]
https://pesquisa.teste.bvsalud.org/bvsms/

**Comment by marcioalvessilva** [comment]
Alterar css do arquivo styleCustom.css

#header{background-color:#4e7952; color: #fff;}
#barAcessibilidade{background-color: #00420c;}
.title1, .title2, .titleBox2, .titleArt a{color: #00420c ;}
#logo img {padding: 5px; background: #fff;}
.box1{border-left: 1px solid #4e7952;}

Exemplo:

![image](https://user-images.githubusercontent.com/48724136/129387982-242444fb-ad15-436e-98fb-285c725a6376.png)
