### ISSUE TITLE
Criar no site da RedDes uma página com a descrição da vaga de Analista de Dados

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/wordpress-themes#73]
Utilizar como modelo a página criada para a vaga de analista de informação em terminologias disponível em 

https://decs.bvsalud.org/vaga-analista-informacao-2021/

Eliminando o item 2. Utilizar a informação de descrição da vaga de acordo com o arquivo anexo.
[ToR_LocalContracts_POR_MTI_AFI_20210202_analista-dados.docx](https://github.com/bireme/wordpress-themes/files/7002164/ToR_LocalContracts_POR_MTI_AFI_20210202_analista-dados.docx)

Colocar a página da vaga de analista de dados em destaque na homepage do site da RedDes

**Comment by marcoslmori** [comment]
Validar 

https://reddes.bvsalud.org/vaga-analista-de-dados-2021/

**Comment by renatomurasaki** [comment]
@marcoslmori muito bom! Por favor, inserir os seguintes textos nas respectivas seções:

3. Resumo das responsabilidades: 
Outras atividades em contexto, quando solicitado.

4. Competencias
Ter receptividade e abertura a novos conhecimentos e aprendizagem; e
Prontidão para agir.

**Comment by renatomurasaki** [comment]
@marcoslmori corrigir o texto:

DE: "coordenação do geral do Gerente da unidade,"
PARA: "coordenação geral do Gerente da unidade,"

**Comment by marcoslmori** [comment]
feito validar

**Comment by renatomurasaki** [comment]
@marcoslmori obrigado!
