### ISSUE TITLE
Incluir menu da BVS SMS-SP nas páginas secundárias

### ISSUE THREAD

**Issue by sousajul** [bireme/wordpress-themes#75]
Incluir o menu da BVS SMS-SP nas páginas secundárias (https://sms.sp.bvs.br/).

**Comment by pierrima** [comment]
Juliana, bom dia
Informo que o menu foi disponibilizado nas páginas secundárias. Por favor, verificar se está ok.

**Comment by sousajul** [comment]
Validado Marina.
