### ISSUE TITLE
BVS ECOS - Enquete

### ISSUE THREAD

**Issue by pierrima** [bireme/wordpress-themes#76]
Boa tarde Marina, tudo bem?

Conforme acordado na reunião que tivemos hoje pela manhã, segue link para o formulário e o código para incluir na BVS ECOS:

https://forms.gle/Mkm4H5ABLT6nrEVp8

<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSeOGwqIlLnXhtDDd4qeZeEviKw1o42EomVFQw9IKPFumhPnWw/viewform?embedded=true" width="640" height="787" frameborder="0" marginheight="0" marginwidth="0">Carregando…</iframe>

Vamos nos falando. Obrigada e um abraço, @barrosjo

**Comment by pierrima** [comment]
Olá Joanita, boa tarde

Publiquei a enquete na área de testes. Por favor, veja se está de acordo:

https://economia.saude.teste.bvs.br/

Abraços

**Comment by barrosjo** [comment]
![BVS_Economia_da_Saúde_Portal_Nacional_de_Informação_em_Economia_da_Saúde_-_2021-09-08_15 52 24](https://user-images.githubusercontent.com/19578003/132567981-14288f95-ba76-4004-8ea4-ece921393359.png)

Boa tarde Marina, 
Dei uma olhada e me parece que ficou muito grande e desproporcional com o restante do conteúdo do portal, além de ter gerado barra de rolagem no formulário. A idéia é que fique discreto ao mesmo tempo que apareça para o usuário da BVS. 
É possível colocar de outra maneira? Talvez se retomarmos a ideia de colocar na lateral como está o do portal regional, lilacs, minha BVS...
Obrigada e um abraço, Joanita

**Comment by pierrima** [comment]
Olá Joanita, bom dia

Conversei com o Mori e ele irá analisar se é possível implementar da forma como foi feito no Regional. Irei finalizar esse chamado e provavelmente vc deverá abrir um outro chamado para ele mas te mantenho informada dos próximos passos.

Abraços
