### ISSUE TITLE
Atualizar página "Núcleos do Programa Telessaúde Brasil Redes" da BVS APS

### ISSUE THREAD

**Issue by sousajul** [bireme/wordpress-themes#77]
Definir nova proposta para a página (https://aps.bvs.br/rede-de-colaboradores/) que foi desenvolvida utilizando um plugin que foi desativado.

Verificar também a seção "SUPER RECOMENDADAS" na home para identificar se não utiliza o mesmo plugin que foi desativado.

**Comment by pierrima** [comment]
Realizado
