### ISSUE TITLE
Implementar a enquete na BVS Economia e Saude.

### ISSUE THREAD

**Issue by barrosjo** [bireme/wordpress-themes#78]
Implementar e publicar na instancia de produção o plugins para posicionar um tab ao lado da home page (CTA plugin for WordPress – Easy Side Tab) e para criar o survey ou polls (Quiz And Survey Master) já foram instalados na instancia de produção.

Enquete já foi criada. 

Embed Shortcode: [qsm quiz=1]

**Comment by pierrima** [comment]
Olá @barrosjo, boa tarde
Informo que os plugins foram implementados e customizados na produção. A enquete já está pública. 
Por favor, verificar se está ok.
Abraços

**Comment by barrosjo** [comment]
Oi @pierrima, boa tarde!
Obrigada! Mudei os títulos, traduzi o texto do botão enviar e ajustei a resposta assim que alguém responder. 
Poderia melhorar o layout ajustando o tamanho da fonte e o espaçamento tanto das perguntas (evitando ou diminuindo a barra de rolagem), quanto da tela de resposta (aparece uma pequena barra de rolagem assim que a resposta é enviada também)?
![BVS_Economia_da_Saúde_Portal_Nacional_de_Informação_em_Economia_da_Saúde_-_2021-09-24_15 55 29](https://user-images.githubusercontent.com/19578003/134726987-365b69ad-4c6e-4561-96ad-534a4ac4b43c.png)
![BVS_Economia_da_Saúde_Portal_Nacional_de_Informação_em_Economia_da_Saúde_-_2021-09-24_15 59 41](https://user-images.githubusercontent.com/19578003/134727013-cd29449f-111f-430f-aab6-9c53026f86bf.png)
Obrigada e abraços, 
Joanita

**Comment by pierrima** [comment]
@barrosjo as mudanças solicitadas foram realizadas. Por favor, verificar se estão ok.

**Comment by barrosjo** [comment]
Obrigada @pierrima . Recurso validado pela contraparte do projeto.
