### ISSUE TITLE
Desenvolver tema para BVS Nicaragua Nacional

### ISSUE THREAD

**Issue by sousajul** [bireme/wordpress-themes#79]
Marina, o mockup para a BVS Nicaragua foi aprovado, solicito dar inicio ao desenvolvimento do tema.

Instância já criada em teste: https://nicaragua.teste.bvsalud.org/
login/senha de autenticação: admin-tst / bireme123

![proposta-home-BVS-Nicaragua](https://user-images.githubusercontent.com/13439949/134552490-25785a0a-bfe8-4e2f-84ae-5a07fa093426.jpg)

**Comment by pierrima** [comment]
@sousajul  Boa tarde, o tema foi desenvolvido no local indicado.
Abraços

**Comment by sousajul** [comment]
@pierrima pode fechar essa issue, tema aplicado, aprovado e em produção.
