### ISSUE TITLE
Desenvolver tema para a BVS Honduras

### ISSUE THREAD

**Issue by sousajul** [bireme/wordpress-themes#84]
Desenvolver tema para a BVS Honduras de acordo com o mockup aprovado - https://honduras.teste.bvsalud.org/.

![propuesta-home-BVS-Honduras](https://user-images.githubusercontent.com/13439949/138960225-8305d4fa-0d80-480a-9b12-809bbc2b491b.png)

**Comment by pierrima** [comment]
Realizado
