### ISSUE TITLE
Desenvolver tema para a BVS Bolívia

### ISSUE THREAD

**Issue by sousajul** [bireme/wordpress-themes#85]
Desenvolver tema para a BVS Bolívia de acordo com o mockup aprovado - https://bolivia.teste.bvsalud.org/

![proposta-BVS-Bolivia](https://user-images.githubusercontent.com/13439949/138961652-2a53f6a5-a2c5-4306-8542-4e2ef5c17183.png)

**Comment by sousajul** [comment]
@pierrima tema aplicado e aprovado, aguardando retorno da contraparte para realizar capacitação para entrada de dados.

**Comment by pierrima** [comment]
Juliana, boa tarde

Posso encerrar esse chamado?

**Comment by sousajul** [comment]
Oi Marina, pode sim.


Abraços

•••••
Juliana Sousa
Supervisora
MIP<http://red.bvsalud.org/> | Monitoramento de Instâncias e Projetos BVS -
BIREME<https://www.paho.org/pt/bireme>/OPAS/OMS<https://www.paho.org/pt> | Departamento de Evidência e Inteligência para Ação em Saúde – EIH/AD

<https://www.paho.org/bra/>

Tel: +55 11 5576-9833 | VoIP: 44872

 [cid:731b0b51-0e4b-4654-b8d0-8c0e77341a8d]
Siga-nos [1499085958495_face.png] <https://www.facebook.com/BIREME/>  [1499085967518_twitter.png] <https://twitter.com/bireme>  [1499085977102_youtube.png] <http://www.youtube.com/channel/UCbFox-neV7EwiFWFZViI2TQ>
________________________________
De: Marina Pierri ***@***.***>
Enviado: quarta-feira, 30 de março de 2022 14:46
Para: bireme/wordpress-themes ***@***.***>
Cc: Sousa, Juliana (BIR) ***@***.***>; Author ***@***.***>
Assunto: Re: [bireme/wordpress-themes] Desenvolver tema para a BVS Bolívia (Issue #85)


Juliana, boa tarde

Posso encerrar esse chamado?

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fwordpress-themes%2Fissues%2F85%23issuecomment-1083435128&data=04%7C01%7Csousajul%40paho.org%7C3610de66a99a4f9e205108da12753112%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637842591813666345%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=E9I3EjIBO2RLgJqr3EHEodXTX%2FyNrxJ%2FChKfhbwnQ9o%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADGRHTIFEFIOAPO2BJEO5B3VCSHORANCNFSM5GYYTGMA&data=04%7C01%7Csousajul%40paho.org%7C3610de66a99a4f9e205108da12753112%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637842591813666345%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=EsobaTdXsJz%2FcVOtRal2pptkTf3HQKpqCJg1Vo8Ikzo%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.
