### ISSUE TITLE
WordPress theme - Criar botão para usuário aceitar o uso de cookies

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/wordpress-themes#86]
Incluir, prioritariamente, nas instâncias que farão uso de dados demográficos, via Google Analytics, pop-up com mensagem padrão e acesso à nossa política de privacidade, explicitando que fazemos uso de cookies, que coletamos dados pessoais, dando a possibilidade do usuário aceitar ou não os cookies.

Ativar este pop-up da forma menos invasiva possível.

Para implementar este botão é necessário alterar a política de privacidade conforme descrito em bireme/terms-policy#1

**Comment by viniciusandrade** [comment]
Solução implementada utiliza o plugin Insert Headers and Footers para inserir nas páginas chamada a JS que implementa a barra de aceitação de cookies.

Solução inicialmente implementada para o Portal Regional e Portal de Pesquisa da BVS.

Demais portais serão implementados gradativamente através de chamado no Ocomon.
