### ISSUE TITLE
Ajuste da informação do label

### ISSUE THREAD

**Issue by pintoros** [bireme/wordpress-themes#9]
Ajustar a informação dos seguintes labels:

Campo URL to search result
Ajustar a explicação do campo para:
Set URL to search results from VHL(BVS) or other infomation sources (if possible)

Campo Responsible
Ajustar a explicação do campo para:
Name, e-mail, code of VHL Cooperative Network (Centro Cooperante)

Search Strategy I , II e III
Para: VHL (BVS) Search Strategy I , II e III

**Comment by wilsonmoura** [comment]
@pintoros Os rótulos foram atualizados conforme solicitação.
