### ISSUE TITLE
Barra de acessibilidade

### ISSUE THREAD

**Issue by barrosjo** [bireme/wordpress-themes#90]
Favor implementar a barra de acessibilidade na BVS Saúde Ambiental e Engenharia de Saúde Pública

**Comment by wilsonmoura** [comment]
Plugin desenvolvido e disponível em: https://github.com/bireme/accessibility-wp-plugin

@pierrima favor solicitar instalação na respectiva instância e realizar os devidos ajustes de layout.

**Comment by barrosjo** [comment]
Me avisem quando tiver disponível na BVS Saúde Ambiental e Engenharia de Saúde Pública para que eu possa comunicar a equipe da FUNASA

**Comment by barrosjo** [comment]
Ajustar os componentes das barras de acessibilidade e cabeçalho conforme solicitação e detalhamento no doc a seguir:

https://paho.sharepoint.com/:w:/r/sites/BIR/TC/TC/Projetos/BRASIL/Funasa/documentacao-tecnica/bvs_saude_ambiental/COMENT%C3%81RIOS_E_ORIENTA%C3%87%C3%95ES_SOBRE_AJUSTES_REALIZADOS_NA_BVS_PELA_BIREMRE.docx?d=wfcb0126000e446c08b3f1463d538fa4a&csf=1&web=1&e=Id7pVm

**Comment by marcioalvessilva** [comment]
CSS da barra inserido, por Wordpress.

**Comment by wilsonmoura** [comment]
@marcioalvessilva obrigado pelo apoio!

@barrosjo favor validar se os ajustes na barra de acessibilidade estão em conformidade com o layout solicitado no documento.

**Comment by barrosjo** [comment]
@wilsonmoura me parece que ok quanto a estrutura. Quanto ao layout acredito que ainda faltam alguns ajustes de tamanho, alinhamento, etc, certo?

**Comment by wilsonmoura** [comment]
@pierrima favor realizar os demais ajustes que foram solicitados pelo cliente.

**Comment by wilsonmoura** [comment]
@pierrima favor realizar os demais ajustes que foram solicitados pelo cliente.

**Comment by wilsonmoura** [comment]
@barrosjo favor verificar se existe algum ajuste pendente.
