### ISSUE TITLE
Ajustar o tema do portal do LIS para trabalhar com a versão nova do plugin polylang

### ISSUE THREAD

**Issue by marcoslmori** [bireme/wordpress-themes#91]
Após resolver o problema, deve ser feito as seguintes atividades por @marcoslmori 

- dar git pull no repositorio de temas
- copiar o portal do lis para portal do vitrinas
- fazer o link para o repositório desse tema duplicado

Envolvidos na operação
@marcioalvessilva 
@pierrima

**Comment by wilsonmoura** [comment]
@marcoslmori tema criado, instalado e ativado conforme solicitado.

Com relação ao problema no posicionamento dos widgets, constatamos que a origem do erro provavelmente está relacionado com o próprio WordPress. Esse bug impede o uso de mais de um widget de texto. Para contornar isso, fiz um teste usando o widget **Layout Builder**.

**Comment by marcoslmori** [comment]
chamado efetuado 8308
