### ISSUE TITLE
Criar barra de filtros para páginas webinars e notícias no portal RedETSA

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/wordpress-themes#97]
Criar barra de filtros para página de Webinars e Notícias no portal RedETSA
**Webinars** - https://redetsa.bvsalud.org/webinars/
**Notícias** - https://redetsa.bvsalud.org/noticias/

**Página de referencias:**
https://www.who.int/es/news
https://criteria.iadb.org/es/webinars
Grato!

**Comment by wilsonmoura** [comment]
@marcioalvessilva ajustes realizados no ambiente de testes. Favor validar.
