### ISSUE TITLE
Avaliar se é possível ajustar banner da BVS Brasil nos plug-ins

### ISSUE THREAD

**Issue by suelisuga** [bireme/wordpress-themes#98]
Solicito avaliar se é possível ajustar banner da BVS Brasil nos plug-ins Multimedia, Legislação, LIS, DirEve
https://brasil.bvs.br/direve
https://brasil.bvs.br/multimedia
https://brasil.bvs.br/lis
https://brasil.bvs.br/leisref
![image](https://user-images.githubusercontent.com/13105683/155557095-8d447613-b217-4412-89a2-0ece82d1dad3.png)

Obrigada

**Comment by marcioalvessilva** [comment]
Olá @suelisuga localizei esse issue aberto para Marina,
Fiz alguns ajustes no header, footer, breadcrumb veja se atende o que foi solicitado.
Não consigo deixar o banner diferente do que consta na home desse portal, mas criei uma linha para o logo não ficar flutuando e dar a sensação de quebra de sessão.
Continuo à disposição.
Se estiver aprovado por favor fechar o issue

**Comment by suelisuga** [comment]
Solicito incluir no breadcrumb o termo Legislação em saúde na página do plug-in de leisref.
https://brasil.bvs.br/leisref 

Exemplos:
![image](https://user-images.githubusercontent.com/13105683/230455085-cdcc8a16-8ecf-4959-97b3-905d7b3cbfb3.png)

![image](https://user-images.githubusercontent.com/13105683/230455220-9890e13e-d782-4a20-b17f-8298f63244f8.png)

![image](https://user-images.githubusercontent.com/13105683/230455298-f45f4e86-b8cc-4c50-ae59-6e1b06ee7f73.png)

Obrigada!
Sueli

**Comment by marcioalvessilva** [comment]
Por favor validar e fechar issue: https://brasil.bvs.br/leisref
