### ISSUE TITLE
Tema WP BVS Moçambique

### ISSUE THREAD

**Issue by sousajul** [bireme/wordpress-themes#99]
Marina, conforme entendimentos com a equipe da BVS Moçambique, solicito ajustar o banner do desenho da proposta em anexo incluindo no banner o nome da BVS Moçambique e o logo eportuguese alinhado à direita.

E no lugar do destaque onde está BVS Moçambique ao lado do RSS incluir uma imagem para simular um carrossel de destaques.

![modelo2](https://user-images.githubusercontent.com/13439949/157063412-25ae35af-c0a8-47e4-98a2-a9041b8140cf.png)

**Comment by pierrima** [comment]
Juliana,

Segue a proposta com as alterações solicitadas. Abraços
![proposta](https://user-images.githubusercontent.com/13052947/160170395-f5585e86-4861-4400-99bd-ecadd460879a.png)

**Comment by sousajul** [comment]
Está ok.
